In [1]:
# import required libriaries
from pathlib import Path
import json

from fpl_predictor.util import *

In [2]:
# path to data directory
#path = Path('/home/jupyter/fpl-prediction/data')
path = Path('./fpl_predictor/data')

In [3]:
# read in latest training set
df_train = pd.read_csv(path/'train_v8.csv', index_col=0, 
                       dtype={'season':str,
                              'comp':str,
                              'squad':str})

# path to current season
season_paths = [path/'2021-22']

# name for current season
season_names = ['2122']

# team codes
teams = pd.read_csv(path/'teams.csv')

# latest remaining season dataset, for latest week's play_proba values
remaining_season = pd.read_csv(path/'remaining_season.csv', index_col=0)

# create players dataset
all_players = build_players(path, season_paths, season_names, teams)

# 2019-20 market value
# table was in slightly different position for 2019-20 season
# should check that 2019-20 season values remain the same once season starts
teams_mv = build_season_mv('2122', 11, range(13,33))

In [4]:
# all_players#[all_players['full_name'] == 'Ben Davies']

In [5]:
# df_train = df_train.iloc[:-686]

In [6]:
# find the latest gameweek
last_gw = df_train['gw'][df_train['season'] == season_names[0]].max()

if np.isnan(last_gw): 
    last_gw = 1 
else: 
    last_gw = last_gw + 1
    
last_gw

26

In [7]:
# build training set for latest gameweek
df_latest = build_season(season_paths[0], season_names[0], all_players, teams, teams_mv, [last_gw])

In [8]:
df_latest.drop_duplicates(inplace=True)

In [9]:
# df_latest[df_latest['player'] == 'Chris Wood']
# lucas digne
# chris wood

In [10]:
last_play_proba = remaining_season[remaining_season['gw'] == last_gw][['player', 'team', 'play_proba']]

In [11]:
last_play_proba.head()

             player             team  play_proba
0        Kurt Zouma  West Ham United        0.75
1        Mark Noble  West Ham United        1.00
2   Darren Randolph  West Ham United        1.00
3  Lukasz Fabianski  West Ham United        1.00
4    Angelo Ogbonna  West Ham United        0.00

In [12]:
# add latest week's play_proba for each player
df_latest = df_latest.merge(last_play_proba, on=['player', 'team'], how='left')

In [13]:
df_latest.drop_duplicates(inplace=True)

In [14]:
df_train.drop_duplicates(inplace=True)

In [15]:
if last_gw==1:
    df_latest['relative_market_value_team_season'] = df_latest['relative_market_value_team']
    df_latest['relative_market_value_opponent_team_season'] = df_latest['relative_market_value_opponent_team']

In [16]:
# for when you're doing the season value properly
# relative_market_value_season = train_df[train_df['season'] == '2021'][['team', 'relative_market_value_team']].groupby(['team']).first()
# relative_market_value_season = relative_market_value_season.rename(columns={'relative_market_value_team': 'season_value'})
# relative_market_value_season

In [17]:
# now get futher stats from fbref
# standard stats
features = ['squad', 'comp', 'round', 'shots_total', 'shots_on_target', 'touches', 'pressures',
            'tackles', 'interceptions', 'blocks', 'xg', 'npxg', 'xa', 'sca', 
            'gca', 'passes_completed', 'passes', 'passes_pct',  'carries', 
            'dribbles_completed', 'dribbles']

In [18]:
# url for the premier league
url_base = 'https://fbref.com'
pl_history_page = '/en/comps/9/history/Premier-League-Seasons'
url = url_base + pl_history_page

# scrape the history table to get latest season
pl_history_table = get_table(url)
pl_history_urls = get_urls(['season'], 'season', pl_history_table, url_base)
season_urls = pl_history_urls[0:1]

df_enhanced = get_stats(features, season_urls, url_base)

2021-2022
https://fbref.com/en/comps/9/Premier-League-Stats
Manchester City
https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats
Ederson
Bernardo Silva
João Cancelo
Rúben Dias
Rodri
Aymeric Laporte
Raheem Sterling
Kyle Walker
Phil Foden
Gabriel Jesus
Jack Grealish
Kevin De Bruyne
İlkay Gündoğan
Riyad Mahrez
Nathan Aké
Fernandinho
Oleksandr Zinchenko
John Stones
Ferrán Torres
Cole Palmer
Zack Steffen
Benjamin Mendy
James Mcatee
Liam Delap
Kayky Chagas
Liverpool
https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
Alisson
Virgil van Dijk
Mohamed Salah
Trent Alexander-Arnold
Sadio Man�
Jo�l Matip
Jordan Henderson
Andrew Robertson
Diogo Jota
Fabinho
Thiago Alc�ntara
Alex Oxlade-Chamberlain
Roberto Firmino
Naby Ke�ta
Kostas Tsimikas
Curtis Jones
Ibrahima Konat�
James Milner
Harvey Elliott
Luis D�az
Caoimh�n Kelleher
Joe Gomez
Tyler Morton
Takumi Minamino
Divock Origi
Kaide Gordon
Neco Williams
Chelsea
https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats
Antonio Rüdiger
Edouard Mendy
Thiago Silva
Jorginho
Marcos Alonso
Mason Mount
César Azpilicueta
Reece James
Kai Havertz
Romelu Lukaku
Mateo Kovačić
Andreas Christensen
N'Golo Kanté
Callum Hudson-Odoi
Trevoh Chalobah
Hakim Ziyech
Christian Pulisic
Ruben Loftus-Cheek
Timo Werner
Ben Chilwell
Kepa Arrizabalaga
Malang Sarr
Saúl Ñíguez
Ross Barkley
Emerson Palmieri
Manchester Utd
https://fbref.com/en/squads/19538871/Manchester-United-Stats
David de Gea
Bruno Fernandes
Harry Maguire
Scott McTominay
Cristiano Ronaldo
Luke Shaw
Fred
Victor Lindelöf
Aaron Wan-Bissaka
Mason Greenwood
Backing off 0.2 seconds afters 1 tries calling function <function get_table at 0x000001D770B2C9D8> with args ('https://fbref.com/en/players/58eee997/matchlogs/2021-2022/summary/Mason-Greenwood-Match-Logs',) and kwargs {}
Backing off 0.9 seconds afters 2 tries calling function <function get_table at 0x000001D770B2C9D8> with args ('https://fbref.com/en/players/58eee997/matchlogs/2021-2022/summary/Mason-Greenwood-Match-Logs',) and kwargs {}
Backing off 3.2 seconds afters 3 tries calling function <function get_table at 0x000001D770B2C9D8> with args ('https://fbref.com/en/players/58eee997/matchlogs/2021-2022/summary/Mason-Greenwood-Match-Logs',) and kwargs {}
Backing off 5.0 seconds afters 4 tries calling function <function get_table at 0x000001D770B2C9D8> with args ('https://fbref.com/en/players/58eee997/matchlogs/2021-2022/summary/Mason-Greenwood-Match-Logs',) and kwargs {}
Jadon Sancho
Raphaël Varane
Diogo Dalot
Paul Pogba
Marcus Rashford
Nemanja Matić
Alex Telles
Edinson Cavani
Anthony Elanga
Eric Bailly
Anthony Martial
Daniel James
Jesse Lingard
Phil Jones
Donny van de Beek
Arsenal
https://fbref.com/en/squads/18bb7c10/Arsenal-Stats
Ben White
Bukayo Saka
Aaron Ramsdale
Gabriel Dos Santos
Thomas Partey
Martin Ødegaard
Kieran Tierney
Takehiro Tomiyasu
Emile Smith Rowe
Alexandre Lacazette
Granit Xhaka
Pierre-Emerick Aubameyang
Martinelli
Albert Sambi Lokonga
Nuno Tavares
Nicolas Pépé
Cédric Soares
Rob Holding
Bernd Leno
Ainsley Maitland-Niles
Pablo Marí
Calum Chambers
Mohamed Elneny
Sead Kolašinac
Folarin Balogun
Eddie Nketiah
Reiss Nelson
West Ham
https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats
Łukasz Fabiański
Declan Rice
Jarrod Bowen
Michail Antonio
Tomáš Souček
Pablo Fornals
Saïd Benrahma
Craig Dawson
Aaron Cresswell
Vladimír Coufal
Kurt Zouma
Angelo Ogbonna
Ben Johnson
Manuel Lanzini
Issa Diop
Arthur Masuaku
Nikola Vlašić
Mark Noble
Ryan Fredericks
Alphonse Areola
Andriy Yarmolenko
Harrison Ashby
Sonny Perkins
Alex Král
Wolves
https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats
Jos� S�
Max Kilman
Conor Coady
Romain Sa�ss
N�lson Semedo
Ra�l Jim�nez
Jo�o Moutinho
R�ben Neves
Rayan A�t Nouri
Francisco Trinc�o
Leander Dendoncker
Hwang Hee-chan
Fernando Mar�al
Daniel Podence
Adama Traor�
Ki-Jana Hoever
Toti Gomes
F�bio Silva
Luke Cundle
Jonny Castro
Chiquinho
Pedro Neto
Morgan Gibbs-White
Tottenham
https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats
Hugo Lloris
Harry Kane
Pierre Højbjerg
Son Heung-min
Eric Dier
Sergio Reguilón
Lucas Moura
Emerson
Oliver Skipp
Davinson Sánchez
Ben Davies
Cristian Romero
Japhet Tanganga
Harry Winks
Dele Alli
Tanguy Ndombele
Ryan Sessegnon
Steven Bergwijn
Rodrigo Bentancur
Matt Doherty
Dejan Kulusevski
Giovani Lo Celso
Bryan
Joe Rodon
Brighton
https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats
Robert Sánchez
Marc Cucurella
Leandro Trossard
Neal Maupay
Joël Veltman
Adam Lallana
Jakub Moder
Yves Bissouma
Lewis Dunk
Pascal Groß
Adam Webster
Shane Duffy
Dan Burn
Alexis Mac Allister
Tariq Lamptey
Solly March
Enock Mwepu
Danny Welbeck
Steven Alzate
Aaron Connolly
Jason Steele
Jeremy Sarmiento
Taylor Richards
Evan Ferguson
Jürgen Locadia
Southampton
https://fbref.com/en/squads/33c895d4/Southampton-Stats
Mohammed Salisu
James Ward-Prowse
Oriol Romeu
Valentino Livramento
Jan Bednarek
Kyle Walker-Peters
Alex McCarthy
Nathan Redmond
Che Adams
Adam Armstrong
Armando Broja
Mohamed Elyounoussi
Romain Perraud
Fraser Forster
Ibrahima Diallo
Nathan Tella
Stuart Armstrong
Jack Stephens
Lyanco
Moussa Djenepo
Theo Walcott
Willy Caballero
Shane Long
Yan Valery
William Smallbone
Crystal Palace
https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats
Tyrick Mitchell
Marc Guéhi
Joel Ward
Vicente Guaita
Conor Gallagher
Joachim Andersen
Wilfried Zaha
Jordan Ayew
Cheikhou Kouyaté
Odsonne Édouard
James McArthur
Christian Benteke
Jeffrey Schlupp
Will Hughes
Michael Olise
Luka Milivojević
James Tomkins
Jean-Philippe Mateta
Jack Butland
Nathaniel Clyne
Eberechi Eze
Jaïro Riedewald
Jesuran Rak Sakyi
Nathan Ferguson
Leicester City
https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats
Kasper Schmeichel
Çağlar Söyüncü
James Maddison
Youri Tielemans
Wilfred Ndidi
Jamie Vardy
Harvey Barnes
Luke Thomas
Daniel Amartey
Timothy Castagne
Ademola Lookman
Boubakary Soumaré
Ricardo Pereira
Kiernan Dewsbury Hall
Jonny Evans
Marc Albrighton
Patson Daka
Kelechi Iheanacho
Jannik Vestergaard
Ryan Bertrand
James Justin
Hamza Choudhury
Ayoze Pérez
Kasey McAteer
Aston Villa
https://fbref.com/en/squads/8602292d/Aston-Villa-Stats
Matty Cash
Emiliano Mart�nez
Tyrone Mings
John McGinn
Ezri Konsa
Ollie Watkins
Douglas Luiz
Jacob Ramsey
Emi Buend�a
Matt Targett
Danny Ings
Marvelous Nakamba
Ashley Young
Axel Tuanzebe
Lucas Digne
Leon Bailey
Kortney Hause
Anwar El Ghazi
Philippe Coutinho
Morgan Sanson
Calum Chambers
Carney Chukwuemeka
Bertrand Traor�
Jed Steer
Cameron Archer
Keinan Davis
Tr�z�guet
Jaden Philogene Bidace
Wesley Moraes
Brentford
https://fbref.com/en/squads/cd051869/Brentford-Stats
Pontus Jansson
Christian Nørgaard
Ethan Pinnock
Sergi Canós
Bryan Mbeumo
Ivan Toney
Rico Henry
Vitaly Janelt
Mathias Jensen
Kristoffer Ajer
Álvaro Fernández
David Raya
Frank Onyeka
Mads Roerslev
Shandon Baptiste
Yoane Wissa
Mathias Jørgensen
Charlie Goode
Mads Bech Sørensen
Saman Ghoddos
Jonas Lössl
Dominic Thompson
Marcus Forss
Josh Dasilva
Mads Bidstrup
Finley Stevens
Leeds United
https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats
Illan Meslier
Stuart Dallas
Raphael Dias Belloli
Jack Harrison
Daniel James
Diego Llorente
Mateusz Klich
Luke Ayling
Rodrigo
Pascal Struijk
Liam Cooper
Adam Forshaw
Junior Firpo
Kalvin Phillips
Robin Koch
Tyler Roberts
Jamie Shackleton
Patrick Bamford
Joe Gelhardt
Cody Drameh
Charlie Cresswell
Leo Fuhr Hjelde
Crysencio Summerville
Lewis Bate
H�lder Costa
Sam Greenwood
Liam McCarron
Stuart McKinstry
Everton
https://fbref.com/en/squads/d3fd31cc/Everton-Stats
Michael Keane
Jordan Pickford
Allan
Demarai Gray
Séamus Coleman
Ben Godfrey
Andros Townsend
Abdoulaye Doucouré
Richarlison
Lucas Digne
Anthony Gordon
Mason Holgate
Alex Iwobi
Salomón Rondón
Dominic Calvert-Lewin
Yerry Mina
André Gomes
Jonjoe Kenny
Fabian Delph
Donny van de Beek
Tom Davies
Jarrad Branthwaite
Asmir Begović
Vitaliy Mykolenko
Jean-Philippe Gbamin
Ellis Simms
Dele Alli
Lewis Dobbin
Tyler Onyango
Anwar El Ghazi
Cenk Tosun
Moise Kean
Newcastle Utd
https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats
Allan Saint-Maximin
Joelinton
Jamaal Lascelles
Joe Willock
Matt Ritchie
Jonjo Shelvey
Fabian Sch�r
Callum Wilson
Javier Manquillo
Martin D�bravka
Ciaran Clark
Ryan Fraser
Isaac Hayden
Miguel Almir�n
Sean Longstaff

Jacob Murphy
Karl Darlow
Emil Krafth
Federico Fern�ndez
Chris Wood
Freddie Woodman
Kieran Trippier
Jamal Lewis
Paul Dummett
Dan Burn
Matt Targett
Jeff Hendrick
Dwight Gayle
Bruno Guimar�es
Burnley
https://fbref.com/en/squads/943e8050/Burnley-Stats
Dwight McNeil
Nick Pope
James Tarkowski
Ben Mee
Ashley Westwood
Josh Brownhill
Matthew Lowton
Chris Wood
Charlie Taylor
Jóhann Berg Guðmundsson
Maxwel Cornet
Jack Cork
Aaron Lennon
Erik Pieters
Jay Rodriguez
Connor Roberts
Nathan Collins
Wout Weghorst
Ashley Barnes
Matěj Vydra
Wayne Hennessey
Dale Stephens
Watford
https://fbref.com/en/squads/2abfe087/Watford-Stats
Moussa Sissoko
Craig Cathcart
Joshua King
Emmanuel Dennis
Juraj Kucka
Kiko Femen�a
William Troost-Ekong
Ben Foster
Ismaila Sarr
Tom Cleverley
Daniel Bachmann
Adam Masina
Imran Louza
Danny Rose
Samir Santos
Hassane Kamara
Jo�o Pedro
Cucho
Jeremy Ngakia
Francisco Sierralta
Edo Kayembe
Ken Sema
Oghenekaro Etebo
Ozan Tufan
Christian Kabasele
Nicolas Nkoulou
Ashley Fletcher
Troy Deeney
Dan Gosling
Norwich City
https://fbref.com/en/squads/1c781004/Norwich-City-Stats
Max Aarons
Teemu Pukki
Kenny McLean
Ben Gibson
Grant Hanley
Tim Krul
Brandon Williams
Pierre Lees-Melou
Milot Rashica
Billy Gilmour
Josh Sargent
Mathias Normann
Ozan Kabak
Dimitris Giannoulis
Adam Idah
Angus Gunn
Przemysław Płacheta
Lukas Rupp
Todd Cantwell
Andrew Omobamidele
Jakob Sørensen
Kieran Dowell
Christos Tzolis
Sam Byram
Jon Rowe
Bali Mumba

In [19]:
# get the player name matching dictionary
with open(path/'match_list.json') as f:
  match_list = json.load(f)

match_list

{'Fabinho': 'Fabio Henrique Tavares',
 'Alisson': 'Alisson Ramses Becker',
 'Joël Matip': 'Joel Matip',
 'Joe Gomez': 'Joseph Gomez',
 'Naby Keïta': 'Naby Keita',
 'Adrián': 'Adrián San Miguel del Castillo',
 'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
 'Allan': 'Allan Marques Loureiro',
 'Richarlison': 'Richarlison de Andrade',
 'Gylfi Sigurðsson': 'Gylfi Sigurdsson',
 'Séamus Coleman': 'Seamus Coleman',
 'André Gomes': 'André Filipe Tavares Gomes',
 'Bernard': 'Bernard Anício Caldeira Duarte',
 'Çağlar Söyüncü': 'Çaglar Söyüncü',
 'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
 'Fred': 'Frederico Rodrigues de Paula Santos',
 'Nemanja Matić': 'Nemanja Matic',
 'Alex Telles': 'Alex Nicolao Telles',
 'Pierre Højbjerg': 'Pierre-Emile Højbjerg',
 'Son Heung-min': 'Heung-Min Son',
 'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
 'Érik Lamela': 'Erik Lamela',
 'Dele Alli': 'Bamidele Alli',
 'Carlos Vinícius': 'Carlos Vinicius Alves Morais',
 'Ederson': 'Ederson Santana de Moraes',
 'Rodri': 'Rodrigo Hernandez',
 'Rúben Dias': 'Rúben Santos Gato Alves Dias',
 'João Cancelo': 'João Pedro Cavaco Cancelo',
 'İlkay Gündoğan': 'Ilkay Gündogan',
 'Gabriel Jesus': 'Gabriel Fernando de Jesus',
 'Ferrán Torres': 'Ferran Torres',
 'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
 'Fernandinho': 'Fernando Luiz Rosa',
 'Eric García': 'Eric Garcia',
 'Matty Cash': 'Matthew Cash',
 'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
 'Ezri Konsa': 'Ezri Konsa Ngoyo',
 'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
 'Ben Chilwell': 'Benjamin Chilwell',
 'Thiago Silva': 'Thiago Emiliano da Silva',
 'Mateo Kovačić': 'Mateo Kovacic',
 'Jorginho': 'Jorge Luiz Frello Filho',
 'Emerson Palmieri': 'Emerson Palmieri dos Santos',
 'Oriol Romeu': 'Oriol Romeu Vidal',
 'Dan Nlundulu': "Daniel N'Lundulu",
 'Łukasz Fabiański': 'Lukasz Fabianski',
 'Tomáš Souček': 'Tomas Soucek',
 'Vladimír Coufal': 'Vladimir Coufal',
 'Felipe Anderson': 'Felipe Anderson Pereira Gomes',
 'Rui Patrício': 'Rui Pedro dos Santos Patrício',
 'Pedro Neto': 'Pedro Lomba Neto',
 'Daniel Podence': 'Daniel Castelo Podence',
 'Nélson Semedo': 'Nélson Cabral Semedo',
 'Rúben Neves': 'Rúben Diogo da Silva Neves',
 'João Moutinho': 'João Filipe Iria Santos Moutinho',
 'Rayan Aït Nouri': 'Rayan Ait Nouri',
 'Fábio Silva': 'Fabio Silva',
 'Rúben Vinagre': 'Rúben Gonçalo Silva Nascimento Vinagre',
 'Vitinha': 'Vitor Ferreira',
 'Rodrigo': 'Rodrigo Moreno',
 'Pablo Hernández': 'Pablo Hernández Domínguez',
 'Ian Carlo Poveda': 'Ian Carlo Poveda-Ocampo',
 'Joelinton': 'Joelinton Cássio Apolinário de Lira',
 'Luka Milivojević': 'Luka Milivojevic',
 'Jaïro Riedewald': 'Jairo Riedewald',
 'Gabriel Dos Santos': 'Gabriel Magalhães',
 'Willian': 'Willian Borges Da Silva',
 'Dani Ceballos': 'Daniel Ceballos Fernández',
 'David Luiz': 'David Luiz Moreira Marinho',
 'Eddie Nketiah': 'Edward Nketiah',
 'Joe Willock': 'Joseph Willock',
 'Sead Kolašinac': 'Sead Kolasinac',
 'Martinelli': 'Gabriel Teodoro Martinelli Silva',
 'Solly March': 'Solomon March',
 'Bernardo': 'Bernardo Fernandes da Silva Junior',
 'Jóhann Berg Guðmundsson': 'Johann Berg Gudmundsson',
 'Matěj Vydra': 'Matej Vydra',
 'Andre-Frank Zambo Anguissa': 'André-Frank Zambo Anguissa',
 'Semi Ajayi': 'Oluwasemilogo Adesewo Ibidapo Ajayi',
 'Branislav Ivanović': 'Branislav Ivanovic',
 'Filip Krovinović': 'Filip Krovinovic',
 'Ahmed Hegazi': 'Ahmed El-Sayed Hegazi',
 'Harvey Elliot': 'Harvey Elliott',
 'Angeliño': 'Angelo Ogbonna',
 'Thomas Doyle': 'Tommy Doyle',
 'Diogo Dalot': 'José Diogo Dalot Teixeira',
 'Pedro': 'Pedro Rodríguez Ledesma',
 'Ricardo Pereira': 'Ricardo Domingos Barbosa Pereira',
 'Gedson Fernandes': 'Gedson Carvalho Fernandes',
 "Georges-Kévin N'Koudou": 'Georges-Kévin Nkoudou',
 'Jonny Castro': 'Jonathan Castro Otto',
 'Jesús Vallejo': 'Jesús Vallejo Lázaro',
 'Bruno Jordão': 'Bruno André Cavaco Jordao',
 'Mattéo Guendouzi': 'Matteo Guendouzi',
 'Richairo Živković': 'Richairo Zivkovic',
 'Danny Drinkwater': 'Daniel Drinkwater',
 'Martin Dúbravka': 'Martin Dubravka',
 'Yoshinori Mutō': 'Yoshinori Muto',
 'Ki Sung-yueng': 'Sung-yueng Ki',
 'Roberto': 'Roberto Jimenez Gago',
 'Javier Hernández': 'Javier Hernández Balcázar',
 'Frederic Guilbert': 'Frédéric Guilbert',
 'Björn Engels': 'Bjorn Engels',
 'Pepe Reina': 'José Reina',
 'Jota': 'José Ignacio Peleteiro Romallo',
 'Arnaut Groeneveld': 'Arnaut Danjuma Groeneveld',
 'Étienne Capoue': 'Etienne Capoue',
 'Kiko Femenía': 'Francisco Femenía Far',
 'Ismaila Sarr': 'Ismaila Sarr',
 'João Pedro': 'João Pedro Junqueira de Jesus',
 'Max Aarons': 'Max Aarons',
 'Emi Buendía': 'Emiliano Buendía Stati',
 'Mario Vrančić': 'Mario Vrancic',
 'Josip Drmić': 'Josip Drmic',
 'Ralf Fährmann': 'Ralf Fahrmann',
 'Danilo': 'Danilo Luiz da Silva',
 'Petr Čech': 'Petr Cech',
 'Idrissa Gana Gueye': 'Idrissa Gueye',
 'Marko Arnautović': 'Marko Arnautovic',
 'Xande Silva': 'Alexandre Nascimento Costa Silva',
 'Julián Speroni': 'Julian Speroni',
 'Kenedy': 'Robert Kenedy Nunes do Nascimento',
 'Joselu': 'Jose Luis Mato Sanmartín',
 'Asmir Begović': 'Asmir Begović',
 'Kayne Ramsey': 'Kayne Ramsay',
 'Bruno': 'Bruno Saltor Grau',
 'Junior Hoilett': 'David Junior Hoilett',
 'Greg Cunningham': 'Greg Cunninghamm',
 'Jazz Richards': 'Ashley Darel Jazz Richards',
 'Jean Seri': 'Jean Michael Seri',
 'Fabricio': 'Fabricio Agosto Ramírez',
 'Lazar Marković': 'Lazar Markovic',
 'Mathias Jørgensen': 'Mathias Jorgensen',
 'Steve Mounié': 'Steve Mounie',
 'Jon Gorenc Stanković': 'Jon Gorenc Stankovic',
 'Matty Daly': 'Matthew Daly',
 'Yaya Touré': 'Gnegneri Yaya Touré',
 'Brahim Díaz': 'Brahim Diaz',
 'Zlatan Ibrahimović': 'Zlatan Ibrahimovic',
 'Marko Grujić': 'Marko Grujic',
 'Charly Musonda Jr.': 'Charly Musonda',
 'Nikola Vlašić': 'Nikola Vlasic',
 'Aleksandar Dragović': 'Aleksandar Dragovic',
 'Eldin Jakupović': 'Eldin Jakupovic',
 'Rob Elliot': 'Robert Elliot',
 'Jesús Gámez': 'Jesús Gámez Duarte',
 'Massadio Haïdara': 'Massadio Haidara',
 'Lee Chung-yong': 'Chung-yong Lee',
 'Freddie Ladapo': 'Olayinka Fredrick Oladotun Ladapo',
 'João Mário': 'João Mário Naval Costa Eduardo',
 'José Fonte': 'Jose Fonte',
 'Younès Kaboul': 'Younes Kaboul',
 'Izzy Brown': 'Isaiah Brown',
 'Dušan Tadić': 'Dusan Tadic',
 'Àngel Rangel': 'Angel Rangel',
 'Badou Ndiaye': 'Papa Alioune Ndiaye',
 'Jesé': 'Jesé Rodríguez Ruiz',
 'Tom Edwards': 'Thomas Edwards',
 'Kostas Stafylidis': 'Konstantinos Stafylidis',
 'Lasse Sørensen': 'Lasse Sorenson',
 'Bojan Krkić': 'Bojan Krkic',
 'Allan Nyom': 'Allan-Roméo Nyom',
 'Ahmed Elmohamady': 'Ahmed El Mohamady',
 'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
 'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
 'Emile Smith-Rowe': 'Emile Smith Rowe',
 'Ivan Cavaleiro': 'Ivan Ricardo Neves Abreu Cavaleiro',
 'Bobby Reid': 'Bobby Decordova-Reid',
 'Ahmed El-Sayed Hegazi': 'Ahmed El-Sayed Hegazy',
 'Kiko Casilla': 'Francisco Casilla Cortés',
 'Willian José': 'Willian José Da Silva',
 'Kostas Tsimikas': 'Konstantinos Tsimikas',
 'Okay Yokuşlu': 'Okay Yokuslu',
 'Khanya Leshabela': 'Thakgalo Leshabela',
 'Jaden Philogene Bidace': 'Jaden Philogene-Bidace',
 'William Thomas Fish': 'William Fish',
 'David Raya': 'David Raya Martin',
 'Oghenekaro Etebo': 'Oghenekaro Peter Etebo',
 'Ismaïla Sarr': 'Ismaila Sarr',
 'Cucho': 'Juan Camilo Hernández Suárez',
 'Enoch Mwepu': 'Enock Mwepu',
 'Emiliano Buendía': 'Emiliano Buendía StatiJosé Malheiro de Sá',
 'José Sá': 'José Malheiro de Sá',
 'Francisco Trincão': 'Francisco Machado Mota de Castro Trincão',
 'Valentino Livramento': 'Tino Livramento',
 'Nuno Tavares': 'Nuno Varela Tavares',
 'Jesuran Rak Sakyi': 'Jesurun Rak-Sakyi',
 'Maximillian Aarons': 'Max Aarons',
 'Josh Sargent': 'Joshua Sargent',
 'Junior Firpo': 'Héctor Junior Firpo Adames',
 'Imran Louza': 'Imrân Louza',
 'Bryan': 'Bryan Gil Salvatierra',
 'Kiernan Dewsbury Hall': 'Kiernan Dewsbury-Hall',
 'Cristiano Ronaldo': 'Cristiano Ronaldo dos Santos Aveiro',
 'Emerson': 'Emerson Aparecido Leite de Souza Junior',
 'Mads Roerslev': 'Mads Roerslev Rasmussen',
 'Odsonne Édouard': 'Odsonne Edouard',
 'Hwang Hee-chan': 'Hee-Chan Hwang',
 'Asmir Begovic': 'Asmir Begović',
 'Caoimhín Kelleher': 'Caoimhin Kelleher',
 'Lyanco': 'Lyanco Evangelista Silveira Neves Vojnovic',
 'Przemysław Płacheta': 'Przemyslaw Placheta',
 'James Mcatee': 'James McAtee',
 'Jakob Sørensen': 'Jacob Sørensen',
 'Alex Král': 'Alex Kral',
 'Jon Rowe': 'Jonathan Rowe',
 'Toti Gomes': 'Toti António Gomes',
 'Philippe Coutinho': 'Philippe Coutinho Correia',
 'Vitaliy Mykolenko': 'Vitalii Mykolenko',
 'Samir Santos': 'Samir Caetano de Souza Santos',
 'Chiquinho': 'Francisco Jorge Tomás Oliveira',
 'Josh Dasilva': 'Pelenda Joshua Dasilva',
 'Bruno Guimarães': 'Bruno Guimarães Rodriguez Moura',
 'Kayky Chagas': 'Kayky da Silva Chagas'}

In [20]:
team_list = {}
team_list['Brighton'] = 'Brighton and Hove Albion'
team_list['Leeds United'] = 'Leeds'
team_list['Manchester Utd'] = 'Manchester United'
team_list['Newcastle Utd'] = 'Newcastle United'
team_list['Norwich City'] = 'Norwich'
team_list['Sheffield Utd'] = 'Sheffield United'
team_list['Tottenham'] = 'Tottenham Hotspur'
team_list['West Brom'] = 'West Bromwich Albion'
team_list['West Ham'] = 'West Ham United'
team_list['Wolves'] = 'Wolverhampton Wanderers'

In [21]:
df_enhanced = df_enhanced.loc[df_enhanced[df_enhanced['round'].str[-2:] != 'on'].index]

In [22]:
# replace non-matching names/teams and extract gw as integer
df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)
df_enhanced['squad'] = df_enhanced['squad'].replace(team_list)
df_enhanced['round'] = df_enhanced['round'].str[-2:].astype('int')

In [23]:
# remove duplicated (happens when players transferred within season)
df_enhanced = df_enhanced.drop_duplicates()

In [24]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6992,2021-2022,Jon Rowe,2021-12-28,Norwich,Premier League,20,0,0,9,5,...,0.1,1,0,3,5,60.0,7,0,1,Jonathan Rowe
6993,2021-2022,Jon Rowe,2022-01-12,Norwich,Premier League,18,0,0,6,4,...,0.0,1,0,1,2,50.0,3,1,1,Jonathan Rowe
6994,2021-2022,Jon Rowe,2022-02-09,Norwich,Premier League,24,0,0,5,7,...,0.0,0,0,1,1,100.0,1,0,0,Jonathan Rowe
6995,2021-2022,Jon Rowe,2022-02-19,Norwich,Premier League,26,0,0,2,0,...,0.0,0,0,1,2,50.0,3,0,0,Jonathan Rowe
6996,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [25]:
# create date field in same format as enhanced data
df_latest['date'] = df_latest['kickoff_time'].str[:10]

In [26]:
# check if any names aren't matching
enhanced_players = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['alt_name'].unique().tolist()
standard_players = df_latest['player'].unique().tolist()

unmatched_players = [x for x in enhanced_players if x not in standard_players]
unmatched_players

['Sadio Man�',
 'Jo�l Matip',
 'Thiago Alc�ntara',
 'Naby Ke�ta',
 'Luis D�az',
 'Jos� S�',
 'Romain Sa�ss',
 'N�lson Semedo',
 'Ra�l Jim�nez',
 'Jo�o Moutinho',
 'R�ben Neves',
 'Rayan A�t Nouri',
 'Fernando Mar�al',
 'Emiliano Mart�nez',
 'Emi Buend�a',
 'Fabian Sch�r',
 'Martin D�bravka',
 'Miguel Almir�n',
 'Bruno Guimar�es',
 'Kiko Femen�a']

In [27]:
# check if any teams aren't matching
enhanced_teams = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['squad'].unique().tolist()
standard_teams = df_latest['team'].unique().tolist()

unmatched_teams = [x for x in enhanced_teams if x not in standard_teams]
unmatched_teams

[]

In [29]:
# any additional corrections
# match_list['Kayky Chagas'] = 'Kayky da Silva Chagas'
# match_list['Josh Dasilva'] = 'Pelenda Joshua Dasilva'
# match_list['Bruno Guimarães'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Samir Santos'] = 'Samir Caetano de Souza Santos'
# match_list['Hwang Hee-chan'] = 'Hee-Chan Hwang'

# match_list['Sadio Man�'] = 'Sadio Mané'
# match_list['Jo�l Matip'] = 'Joel Matip'
# match_list['Thiago Alc�ntara'] = 'Thiago Alcántara do Nascimento'
# match_list['Naby Ke�ta'] = 'Naby Keita'
# match_list['Luis D�az'] = 'Luis Díaz'
# match_list['Jos� S�'] = 'José Malheiro de Sá'
# match_list['Romain Sa�ss'] = 'Romain Saïss'
# match_list['N�lson Semedo'] = 'Nélson Cabral Semedo'
# match_list['Ra�l Jim�nez'] = 'Raúl Jiménez'
# match_list['Jo�o Moutinho'] = 'João Filipe Iria Santos Moutinho'
# match_list['R�ben Neves'] = 'Rúben Diogo da Silva Neves'
# match_list['Rayan A�t Nouri'] = 'Rayan Ait Nouri'
# match_list['Fernando Mar�al'] = 'Fernando Marçal'
# match_list['Emiliano Mart�nez'] = 'Emiliano Martínez'
# match_list['Emi Buend�a'] = 'Emiliano Buendía Stati'
# match_list['Fabian Sch�r'] = 'Fabian Schär'
# match_list['Martin D�bravka'] = 'Martin Dubravka'
# match_list['Miguel Almir�n'] = 'Miguel Almirón'
# match_list['Bruno Guimar�es'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Kiko Femen�a'] = 'Francisco Femenía Far'

In [30]:
# replace additional non-matching names
# df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)

In [31]:
# make sure there are no non matches after update
# enhanced_players =  df_enhanced[df_enhanced['round'] == last_gw]['alt_name'].unique().tolist()
# standard_players = df_latest['player'].unique().tolist()

# unmatched_players = [x for x in enhanced_players if x not in standard_players]
# unmatched_players

[]

In [ ]:
# if match list was updated then update the file
# json_file = json.dumps(match_list)
# f = open(path/"match_list.json","w")
# f.write(json_file)
# f.close()

In [32]:
# check there are no duplicates in the join fields for the enhanced data
assert(len(df_enhanced[df_enhanced.duplicated(subset=['alt_name', 'date'], keep=False)]) == 0)

In [33]:
df_latest[df_latest.duplicated(subset=['date','player','team'], keep=False)]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date]
Index: []

[0 rows x 36 columns]

In [34]:
# check there are no duplicates in the join fields for the standard data
assert(len(df_train[df_train.duplicated(subset=['date','player','team'])]) == 0)

In [35]:
# df_train[df_train.duplicated(subset=['date','player','team'])]

In [36]:
# join standard and enhanced dataframes
df_latest_further = df_latest.merge(df_enhanced.drop(['player', 'season', 'round'], axis=1), 
                                   left_on=['date', 'player', 'team'], 
                                   right_on=['date', 'alt_name', 'squad'], how='left')

In [37]:
# drop the alt name field and check the length of the standard
# dataframe has not increased
df_latest_further = df_latest_further.drop(['alt_name'], axis=1)
assert(len(df_latest_further) == len(df_latest_further))

In [38]:
# add crowds field
df_latest_further['crowds'] = 1

In [39]:
assert(sum(df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()) == 0)

In [40]:
df_latest_further[df_latest_further['minutes'] > 0][df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date, squad, comp, shots_total, shots_on_target, touches, pressures, tackles, interceptions, blocks, xg, npxg, xa, sca, gca, passes_completed, passes, passes_pct, carries, dribbles_completed, dribbles, crowds]
Index: []

[0 rows x 57 columns]

In [41]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6992,2021-2022,Jon Rowe,2021-12-28,Norwich,Premier League,20,0,0,9,5,...,0.1,1,0,3,5,60.0,7,0,1,Jonathan Rowe
6993,2021-2022,Jon Rowe,2022-01-12,Norwich,Premier League,18,0,0,6,4,...,0.0,1,0,1,2,50.0,3,1,1,Jonathan Rowe
6994,2021-2022,Jon Rowe,2022-02-09,Norwich,Premier League,24,0,0,5,7,...,0.0,0,0,1,1,100.0,1,0,0,Jonathan Rowe
6995,2021-2022,Jon Rowe,2022-02-19,Norwich,Premier League,26,0,0,2,0,...,0.0,0,0,1,2,50.0,3,0,0,Jonathan Rowe
6996,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [42]:
df_train_new = pd.concat([df_train, df_latest_further], ignore_index=True, axis=0, sort=False)

In [43]:
df_train_new[df_train_new['player'] == 'Harry Kane'].tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
127815,Harry Kane,23,4,90,Tottenham Hotspur,Chelsea,NaN,NaN,False,2,...,0.2,2.0,0.0,13.0,21.0,61.9,25.0,2.0,2.0,1
128541,Harry Kane,24,4,90,Tottenham Hotspur,Southampton,NaN,NaN,True,2,...,0.5,4.0,1.0,18.0,30.0,60.0,20.0,2.0,2.0,1
129202,Harry Kane,25,4,90,Tottenham Hotspur,Wolverhampton Wanderers,NaN,NaN,True,2,...,0.1,2.0,0.0,16.0,26.0,61.5,33.0,2.0,4.0,1
129993,Harry Kane,26,4,90,Tottenham Hotspur,Manchester City,NaN,NaN,False,13,...,0.1,3,1,20,30,66.7,24,0,0,1
129994,Harry Kane,26,4,90,Tottenham Hotspur,Burnley,NaN,NaN,False,2,...,0.1,4,0,22,36,61.1,36,3,3,1

In [44]:
df_train_new.tail(10)

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
130654,Yoane Wissa,26,3,90,Brentford,Arsenal,NaN,NaN,False,2,...,0.0,0,0,13,18,72.2,18,1,1,1
130655,Youri Tielemans,26,3,90,Leicester City,Wolverhampton Wanderers,NaN,NaN,False,2,...,0.1,5,1,44,66,66.7,43,0,0,1
130656,Yves Bissouma,26,3,90,Brighton and Hove Albion,Burnley,NaN,NaN,True,2,...,0.0,1,0,54,61,88.5,53,0,0,1
130657,Zach Awe,26,2,0,Arsenal,Brentford,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130658,Zach Awe,26,2,0,Arsenal,Wolverhampton Wanderers,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130659,Zack Steffen,26,1,0,Manchester City,Tottenham Hotspur,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130660,Zak Swanson,26,2,0,Arsenal,Brentford,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130661,Zak Swanson,26,2,0,Arsenal,Wolverhampton Wanderers,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130662,Álvaro Fernández,26,1,0,Brentford,Arsenal,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
130663,Çaglar Söyüncü,26,2,90,Leicester City,Wolverhampton Wanderers,NaN,NaN,False,0,...,0.0,1,0,67,71,94.4,54,0,0,1

In [45]:
df_latest_further.shape

(1005, 57)

In [46]:
df_train_new.shape

(130664, 59)

In [47]:
# save latest training set to csv
# overwrite existing one
df_train_new.to_csv(path/'train_v8.csv')

In [48]:
# get fixtures
fixtures = pd.read_csv(path/'2021-22/fixtures.csv')
team_dict = teams[['team_2122', 'team']].dropna().set_index('team_2122').to_dict()['team']

fixtures['home_team'] = fixtures['team_h'].replace(team_dict)
fixtures['away_team'] = fixtures['team_a'].replace(team_dict)
fixtures = fixtures[['home_team', 'away_team', 'kickoff_time', 'event']]
fixtures = fixtures.rename(columns={'event':'gw'})


# use these two lines if updating play_proba later in week
# current_gw = last_gw
# df_train_new = pd.read_csv(path/'train_v7.csv', index_col=0, dtype={'season':str,
#                                                                     'comp':str,
#                                                                     'squad':str})

# set starting gameweek (where are we right now in the season)
current_gw = last_gw + 1
fixtures = fixtures[fixtures['gw'] >= current_gw].sort_values(by=['gw'])
fixtures['match_no'] = np.arange(fixtures.shape[0])

In [49]:
fixtures.head(50)

,home_team,away_team,kickoff_time,gw,match_no
255,Southampton,Norwich,2022-02-25T20:00:00Z,27.0,0
256,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,27.0,1
257,Brentford,Newcastle United,2022-02-26T15:00:00Z,27.0,2
258,Brighton and Hove Albion,Aston Villa,2022-02-26T15:00:00Z,27.0,3
259,Crystal Palace,Burnley,2022-02-26T15:00:00Z,27.0,4
260,Manchester United,Watford,2022-02-26T15:00:00Z,27.0,5
261,Everton,Manchester City,2022-02-26T17:30:00Z,27.0,6
262,West Ham United,Wolverhampton Wanderers,2022-02-27T14:00:00Z,27.0,7
263,Burnley,Leicester City,2022-03-01T19:45:00Z,27.0,8
276,Leeds,Aston Villa,2022-03-10T19:45:00Z,28.0,9
275,Wolverhampton Wanderers,Watford,2022-03-10T19:30:00Z,28.0,10
274,Southampton,Newcastle United,2022-03-10T19:30:00Z,28.0,11
273,Tottenham Hotspur,Everton,2022-03-07T20:00:00Z,28.0,12
272,Manchester City,Manchester United,2022-03-06T16:30:00Z,28.0,13
271,Watford,Arsenal,2022-03-06T14:00:00Z,28.0,14
268,Norwich,Brentford,2022-03-05T15:00:00Z,28.0,15
269,Wolverhampton Wanderers,Crystal Palace,2022-03-05T15:00:00Z,28.0,16
267,Newcastle United,Brighton and Hove Albion,2022-03-05T15:00:00Z,28.0,17
266,Burnley,Chelsea,2022-03-05T15:00:00Z,28.0,18
265,Aston Villa,Southampton,2022-03-05T15:00:00Z,28.0,19
264,Leicester City,Leeds,2022-03-05T12:30:00Z,28.0,20
270,Liverpool,West Ham United,2022-03-05T17:30:00Z,28.0,21
285,Arsenal,Leicester City,2022-03-13T16:30:00Z,29.0,22
289,Everton,Newcastle United,2022-03-17T19:45:00Z,29.0,23
288,Arsenal,Liverpool,2022-03-16T20:15:00Z,29.0,24
287,Brighton and Hove Albion,Tottenham Hotspur,2022-03-16T19:30:00Z,29.0,25
286,Crystal Palace,Manchester City,2022-03-14T20:00:00Z,29.0,26
283,Southampton,Watford,2022-03-13T14:00:00Z,29.0,27
284,West Ham United,Aston Villa,2022-03-13T14:00:00Z,29.0,28
281,Everton,Wolverhampton Wanderers,2022-03-13T14:00:00Z,29.0,29
280,Chelsea,Newcastle United,2022-03-13T14:00:00Z,29.0,30
279,Manchester United,Tottenham Hotspur,2022-03-12T17:30:00Z,29.0,31
278,Brentford,Burnley,2022-03-12T15:00:00Z,29.0,32
277,Brighton and Hove Albion,Liverpool,2022-03-12T12:30:00Z,29.0,33
282,Leeds,Norwich,2022-03-13T14:00:00Z,29.0,34
298,Watford,Everton,2022-03-20T14:00:00Z,30.0,35
299,Liverpool,Manchester United,2022-03-20T16:30:00Z,30.0,36
296,Newcastle United,Crystal Palace,2022-03-20T14:00:00Z,30.0,37
295,Burnley,Southampton,2022-03-19T17:30:00Z,30.0,38
297,Tottenham Hotspur,West Ham United,2022-03-20T14:00:00Z,30.0,39
293,Manchester City,Brighton and Hove Albion,2022-03-19T15:00:00Z,30.0,40
292,Leicester City,Brentford,2022-03-19T15:00:00Z,30.0,41
291,Aston Villa,Arsenal,2022-03-19T12:30:00Z,30.0,42
290,Wolverhampton Wanderers,Leeds,2022-03-18T20:00:00Z,30.0,43
294,Norwich,Chelsea,2022-03-19T15:00:00Z,30.0,44
309,Crystal Palace,Arsenal,2022-04-04T19:00:00Z,31.0,45
300,Liverpool,Watford,2022-04-02T11:30:00Z,31.0,46
301,Brighton and Hove Albion,Norwich,2022-04-02T14:00:00Z,31.0,47
302,Burnley,Manchester City,2022-04-02T14:00:00Z,31.0,48
303,Chelsea,Brentford,2022-04-02T14:00:00Z,31.0,49

In [50]:
# add universal team codes for home and away teams
fixtures = fixtures.merge(teams, left_on='home_team', right_on='team', how='left')
fixtures = fixtures.merge(teams, left_on='away_team', right_on='team', how='left')
fixtures = fixtures[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 'team_code_x', 'team_code_y']]
fixtures.rename(index=str,
                columns={'team_code_x':'home_team_code',
                         'team_code_y':'away_team_code'},
                inplace=True)

In [51]:
fixtures.head()

,gw,match_no,home_team,away_team,kickoff_time,home_team_code,away_team_code
0,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,20,45
1,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,2,6
2,27.0,2,Brentford,Newcastle United,2022-02-26T15:00:00Z,94,4
3,27.0,3,Brighton and Hove Albion,Aston Villa,2022-02-26T15:00:00Z,36,7
4,27.0,4,Crystal Palace,Burnley,2022-02-26T15:00:00Z,31,90

In [52]:
# all_players.replace(to_replace='None', value=1, inplace=True)

In [53]:
all_players[all_players['play_proba_2122'] == '0']

,full_name,play_proba_2122,position_2122,id_2122,cost_2122,team_2122,web_name_2122
1,Rúnar Alex Rúnarsson,0,1,2,40,3,Rúnarsson
2,Willian Borges Da Silva,0,3,3,63,3,Willian
3,Pierre-Emerick Aubameyang,0,4,4,96,3,Aubameyang
7,Pablo Marí,0,2,8,42,3,Marí
8,Héctor Bellerín,0,2,9,48,3,Bellerín
...,...,...,...,...,...,...,...
701,Christian Marques,0,2,549,40,39,Marques
703,Louie Moulden,0,1,611,40,39,Moulden
706,Bruno André Cavaco Jordão,0,3,661,45,39,Jordão
708,Dion Sanderson,0,2,686,40,39,Sanderson
709,Ryan Giles,0,3,687,45,39,Giles

In [54]:
# join home team to all players for current season
home_df = fixtures.merge(all_players, 
               left_on='home_team_code', 
               right_on='team_2122', 
               how='left')

# pull out the required fields and rename columns
home_df = home_df[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 
                   'full_name', 'position_2122', 'cost_2122', 'play_proba_2122', 
                   'web_name_2122']]
home_df.rename(index=str, 
               columns={'home_team':'team',
                        'away_team':'opponent_team',
                        'full_name':'player',
                        'position_2122':'position',
                        'cost_2122':'price',
                        'play_proba_2122':'play_proba',
                        'web_name_2122':'short_name'},
              inplace=True)

# add home flag
home_df['was_home'] = True

In [55]:
# join away team to all players for current season
away_df = fixtures.merge(all_players, 
               left_on='away_team_code', 
               right_on='team_2122', 
               how='left')

# pull out the required fields and rename columns
away_df = away_df[['gw',  'match_no', 'away_team', 'home_team', 'kickoff_time', 
                   'full_name', 'position_2122', 'cost_2122', 'play_proba_2122', 
                   'web_name_2122']]
away_df.rename(index=str, 
               columns={'away_team':'team',
                        'home_team':'opponent_team',
                        'full_name':'player',
                        'position_2122':'position',
                        'cost_2122':'price',
                        'play_proba_2122':'play_proba',
                        'web_name_2122':'short_name'},
              inplace=True)

# add home flag
away_df['was_home'] = False

In [56]:
# look at away players
away_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,27.0,0,Norwich,Southampton,2022-02-25T20:00:00Z,Billy Gilmour,3,43,100,Gilmour,False
1,27.0,0,Norwich,Southampton,2022-02-25T20:00:00Z,Brandon Williams,2,39,100,Williams,False
2,27.0,0,Norwich,Southampton,2022-02-25T20:00:00Z,Michael McGovern,1,39,None,McGovern,False
3,27.0,0,Norwich,Southampton,2022-02-25T20:00:00Z,Tim Krul,1,45,100,Krul,False
4,27.0,0,Norwich,Southampton,2022-02-25T20:00:00Z,Teemu Pukki,4,58,100,Pukki,False

In [57]:
# look at home players
home_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Theo Walcott,3,58,100,Walcott,True
1,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Fraser Forster,1,44,100,Forster,True
2,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Alex McCarthy,1,44,0,McCarthy,True
3,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Oriol Romeu Vidal,3,45,100,Romeu,True
4,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Nathan Redmond,3,59,100,Redmond,True

In [58]:
# # calculate average minutes over last 5 gameweeks
# # first get last 5 gameweeks in current season
# recent_mins = df_train_new[(df_train_new['gw'] >= current_gw - 5) & 
#                            (df_train_new['season'] == season_names[0])][['player', 'minutes', 'play_proba']]

# # recent_mins = df_train_new[((df_train_new['gw'] >= 40 - 5) & 
# #                            (df_train_new['season'] == '1920')) | 
# #                            ((df_train_new['gw'] >= 1) & 
# #                            (df_train_new['season'] == '2021'))][['player', 'minutes', 'play_proba']]

# # exclude weeks where the player had an injury designation (i.e. keep where play_proba is 1)
# recent_mins = recent_mins[recent_mins['play_proba'] == 1]

# len(recent_mins)

# # average for each player
# recent_mins = recent_mins.groupby(['player'])['minutes'].mean().to_dict()

# recent_mins

In [59]:
# concatenate home and away players
remaining_season_df = home_df.append(away_df).reset_index(drop=True)

# add home and away team market values
remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2122'],
                                                left_on='team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2122'],
                                                left_on='opponent_team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df.rename(index=str, 
                           columns={'relative_market_value_x':'relative_market_value_team',
                                    'relative_market_value_y':'relative_market_value_opponent_team'},
                           inplace=True)

# add season name
remaining_season_df['season'] = season_names[0]

# divide cost by 10 for actual cost
remaining_season_df['price'] = remaining_season_df['price']/10

# set availability probability
# 0 = 0% chance, 25 = 25% chance, etc
# 'None' or '100' = 100% chance
remaining_season_df.loc[remaining_season_df['play_proba'] == 'None', 'play_proba'] = 100
remaining_season_df['play_proba'] = remaining_season_df['play_proba'].astype('float') / 100

# cast position to integer
remaining_season_df['position'] = remaining_season_df['position'].astype(int)

# # add minutes based on last five fixtures
# remaining_season_df['minutes'] = remaining_season_df['player'].map(recent_mins)
# remaining_season_df['minutes'].fillna(0, inplace=True)

# # multiply minutes by play probability
# remaining_season_df['minutes'] = remaining_season_df['minutes'] * remaining_season_df['play_proba']

In [60]:
remaining_season_df.head(50)

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home,relative_market_value_team,relative_market_value_opponent_team,season
0,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Theo Walcott,3,5.8,1.0,Walcott,True,NaN,NaN,2122
1,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Fraser Forster,1,4.4,1.0,Forster,True,NaN,NaN,2122
2,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Alex McCarthy,1,4.4,0.0,McCarthy,True,NaN,NaN,2122
3,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Oriol Romeu Vidal,3,4.5,1.0,Romeu,True,NaN,NaN,2122
4,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Nathan Redmond,3,5.9,1.0,Redmond,True,NaN,NaN,2122
5,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Jack Stephens,2,4.4,1.0,Stephens,True,NaN,NaN,2122
6,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Stuart Armstrong,3,5.8,1.0,S.Armstrong,True,NaN,NaN,2122
7,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,James Ward-Prowse,3,6.5,1.0,Ward-Prowse,True,NaN,NaN,2122
8,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Kyle Walker-Peters,2,4.8,1.0,Walker-Peters,True,NaN,NaN,2122
9,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Jan Bednarek,2,4.4,1.0,Bednarek,True,NaN,NaN,2122
10,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Daniel N'Lundulu,4,4.5,0.0,Nlundulu,True,NaN,NaN,2122
11,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Che Adams,4,6.9,1.0,Adams,True,NaN,NaN,2122
12,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Nathan Tella,3,4.7,0.0,Tella,True,NaN,NaN,2122
13,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,William Smallbone,3,4.5,1.0,Smallbone,True,NaN,NaN,2122
14,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Michael Obafemi,4,4.5,0.0,Obafemi,True,NaN,NaN,2122
15,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Ibrahima Diallo,3,4.5,1.0,Diallo,True,NaN,NaN,2122
16,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Moussa Djenepo,3,5.2,1.0,Djenepo,True,NaN,NaN,2122
17,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Mohammed Salisu,2,4.5,1.0,Salisu,True,NaN,NaN,2122
18,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Romain Perraud,2,4.8,1.0,Perraud,True,NaN,NaN,2122
19,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Tino Livramento,2,4.3,1.0,Livramento,True,NaN,NaN,2122
20,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Mohamed Elyounoussi,3,5.4,1.0,Elyounoussi,True,NaN,NaN,2122
21,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Armando Broja,4,5.5,1.0,Broja,True,NaN,NaN,2122
22,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Shane Long,4,5.4,1.0,Long,True,NaN,NaN,2122
23,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Adam Armstrong,4,5.7,1.0,A.Armstrong,True,NaN,NaN,2122
24,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Yan Valery,2,3.9,1.0,Valery,True,NaN,NaN,2122
25,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Lyanco Evangelista Silveira Neves Vojnovic,2,4.4,0.0,Lyanco,True,NaN,NaN,2122
26,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Harry Lewis,1,3.9,1.0,Lewis,True,NaN,NaN,2122
27,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Willy Caballero,1,4.3,1.0,Caballero,True,NaN,NaN,2122
28,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Dynel Simeu,2,4.0,0.0,Simeu,True,NaN,NaN,2122
29,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Thierry Small,2,4.0,1.0,Small,True,NaN,NaN,2122
30,27.0,0,Southampton,Norwich,2022-02-25T20:00:00Z,Kgaogelo Chauke,3,4.5,1.0,Chauke,True,NaN,NaN,2122
31,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Pablo Hernández Domínguez,3,5.5,0.0,Hernández,True,NaN,NaN,2122
32,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Francisco Casilla Cortés,1,4.5,0.0,Casilla,True,NaN,NaN,2122
33,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Liam Cooper,2,4.4,0.0,Cooper,True,NaN,NaN,2122
34,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Luke Ayling,2,4.3,1.0,Ayling,True,NaN,NaN,2122
35,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Mateusz Klich,3,5.2,1.0,Klich,True,NaN,NaN,2122
36,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Rodrigo Moreno,4,6.2,1.0,Rodrigo,True,NaN,NaN,2122
37,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Stuart Dallas,3,4.9,1.0,Dallas,True,NaN,NaN,2122
38,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Patrick Bamford,4,7.7,0.0,Bamford,True,NaN,NaN,2122
39,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Diego Llorente,2,4.5,1.0,Llorente,True,NaN,NaN,2122
40,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Kalvin Phillips,3,4.7,0.0,Phillips,True,NaN,NaN,2122
41,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Hélder Wander Sousa de Azevedo e Costa,3,5.4,0.0,Costa,True,NaN,NaN,2122
42,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Tyler Roberts,3,4.8,1.0,Roberts,True,NaN,NaN,2122
43,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Robin Koch,2,4.3,1.0,Koch,True,NaN,NaN,2122
44,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Ian Carlo Poveda-Ocampo,3,4.5,0.0,Poveda,True,NaN,NaN,2122
45,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Raphael Dias Belloli,3,6.5,1.0,Raphinha,True,NaN,NaN,2122
46,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Jamie Shackleton,3,4.4,1.0,Shackleton,True,NaN,NaN,2122
47,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Pascal Struijk,2,4.3,1.0,Struijk,True,NaN,NaN,2122
48,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Illan Meslier,1,4.8,1.0,Meslier,True,NaN,NaN,2122
49,27.0,1,Leeds,Tottenham Hotspur,2022-02-26T12:30:00Z,Jack Harrison,3,5.5,1.0,Harrison,True,NaN,NaN,2122

In [61]:
# save latest prediction set to csv
remaining_season_df.to_csv(path/'remaining_season.csv')