In [1]:
# import required libriaries
from pathlib import Path
import json

from fpl_predictor.util import *

In [2]:
# path to data directory
#path = Path('/home/jupyter/fpl-prediction/data')
path = Path('./fpl_predictor/data')

In [3]:
# read in latest training set
df_train = pd.read_csv(path/'train_v8.csv', index_col=0, 
                       dtype={'season':str,
                              'comp':str,
                              'squad':str})

# path to current season
season_paths = [path/'2021-22']

# name for current season
season_names = ['2122']

# team codes
teams = pd.read_csv(path/'teams.csv')

# latest remaining season dataset, for latest week's play_proba values
remaining_season = pd.read_csv(path/'remaining_season.csv', index_col=0)

# create players dataset
all_players = build_players(path, season_paths, season_names, teams)

# 2019-20 market value
# table was in slightly different position for 2019-20 season
# should check that 2019-20 season values remain the same once season starts
teams_mv = build_season_mv('2122', 11, range(13,33))

In [4]:
# all_players#[all_players['full_name'] == 'Ben Davies']

In [5]:
# df_train = df_train.iloc[:-686]

In [6]:
# find the latest gameweek
last_gw = df_train['gw'][df_train['season'] == season_names[0]].max()

if np.isnan(last_gw): 
    last_gw = 1 
else: 
    last_gw = last_gw + 1
    
last_gw

33

In [7]:
# build training set for latest gameweek
df_latest = build_season(season_paths[0], season_names[0], all_players, teams, teams_mv, [last_gw])

In [8]:
df_latest.drop_duplicates(inplace=True)

In [9]:
# df_latest[df_latest['player'] == 'Chris Wood']
# lucas digne
# chris wood

In [10]:
last_play_proba = remaining_season[remaining_season['gw'] == last_gw][['player', 'team', 'play_proba']]

In [11]:
last_play_proba.head()

              player               team  play_proba
0         Ben Davies  Tottenham Hotspur         1.0
1           Joe Hart  Tottenham Hotspur         0.0
2        Hugo Lloris  Tottenham Hotspur         1.0
3  Toby Alderweireld  Tottenham Hotspur         0.0
4        Erik Lamela  Tottenham Hotspur         0.0

In [12]:
# add latest week's play_proba for each player
df_latest = df_latest.merge(last_play_proba, on=['player', 'team'], how='left')

In [13]:
df_latest.drop_duplicates(inplace=True)

In [14]:
df_train.drop_duplicates(inplace=True)

In [15]:
if last_gw==1:
    df_latest['relative_market_value_team_season'] = df_latest['relative_market_value_team']
    df_latest['relative_market_value_opponent_team_season'] = df_latest['relative_market_value_opponent_team']

In [16]:
# for when you're doing the season value properly
# relative_market_value_season = train_df[train_df['season'] == '2021'][['team', 'relative_market_value_team']].groupby(['team']).first()
# relative_market_value_season = relative_market_value_season.rename(columns={'relative_market_value_team': 'season_value'})
# relative_market_value_season

In [17]:
# now get futher stats from fbref
# standard stats
features = ['squad', 'comp', 'round', 'shots_total', 'shots_on_target', 'touches', 'pressures',
            'tackles', 'interceptions', 'blocks', 'xg', 'npxg', 'xa', 'sca', 
            'gca', 'passes_completed', 'passes', 'passes_pct',  'carries', 
            'dribbles_completed', 'dribbles']

In [18]:
# url for the premier league
url_base = 'https://fbref.com'
pl_history_page = '/en/comps/9/history/Premier-League-Seasons'
url = url_base + pl_history_page

# scrape the history table to get latest season
pl_history_table = get_table(url)
pl_history_urls = get_urls(['season'], 'season', pl_history_table, url_base)
season_urls = pl_history_urls[0:1]

df_enhanced = get_stats(features, season_urls, url_base)

2021-2022
https://fbref.com/en/comps/9/Premier-League-Stats
Manchester City
https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats
Ederson
João Cancelo
Bernardo Silva
Rodri
Aymeric Laporte
Rúben Dias
Phil Foden
Kevin De Bruyne
Kyle Walker
Raheem Sterling
Jack Grealish
İlkay Gündoğan
Gabriel Jesus
Riyad Mahrez
John Stones
Nathan Aké
Oleksandr Zinchenko
Fernandinho
Ferrán Torres
Cole Palmer
Zack Steffen
Benjamin Mendy
James Mcatee
Liam Delap
Kayky Chagas
Liverpool
https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
Alisson
Virgil van Dijk
Mohamed Salah
Trent Alexander-Arnold
Sadio Mané
Joël Matip
Jordan Henderson
Andrew Robertson
Fabinho
Diogo Jota
Thiago Alcántara
Naby Keïta
Roberto Firmino
Alex Oxlade-Chamberlain
Ibrahima Konaté
Curtis Jones
Kostas Tsimikas
James Milner
Luis Díaz
Harvey Elliott
Joe Gomez
Caoimhín Kelleher
Tyler Morton
Takumi Minamino
Divock Origi
Kaide Gordon
Neco Williams
Chelsea
https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats
Antonio Rüdiger
Edouard Mendy
Thiago Silva
Mason Mount
Jorginho
Marcos Alonso
César Azpilicueta
Kai Havertz
N'Golo Kanté
Andreas Christensen
Reece James
Mateo Kovačić
Trevoh Chalobah
Romelu Lukaku
Hakim Ziyech
Timo Werner
Callum Hudson-Odoi
Ruben Loftus-Cheek
Christian Pulisic
Ben Chilwell
Malang Sarr
Kepa Arrizabalaga
Saúl Ñíguez
Ross Barkley
Emerson Palmieri
Tottenham
https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats
Hugo Lloris
Harry Kane
Pierre Højbjerg
Eric Dier
Son Heung-min
Ben Davies
Sergio Reguilón
Emerson
Cristian Romero
Lucas Moura
Oliver Skipp
Davinson Sánchez
Dejan Kulusevski
Rodrigo Bentancur
Japhet Tanganga
Harry Winks
Matt Doherty
Dele Alli
Ryan Sessegnon
Tanguy Ndombele
Steven Bergwijn
Giovani Lo Celso
Bryan
Joe Rodon
Dane Scarlett
Arsenal
https://fbref.com/en/squads/18bb7c10/Arsenal-Stats
Ben White
Bukayo Saka
Gabriel Dos Santos
Aaron Ramsdale
Martin Ødegaard
Thomas Partey
Kieran Tierney
Granit Xhaka
Alexandre Lacazette
Emile Smith Rowe
Martinelli
Takehiro Tomiyasu
Albert Sambi Lokonga
Cédric Soares
Pierre-Emerick Aubameyang
Nuno Tavares
Nicolas Pépé
Rob Holding
Bernd Leno
Eddie Nketiah
Ainsley Maitland-Niles
Mohamed Elneny
Pablo Marí
Calum Chambers
Sead Kolašinac
Folarin Balogun
Reiss Nelson
Manchester Utd
https://fbref.com/en/squads/19538871/Manchester-United-Stats
David de Gea
Bruno Fernandes
Harry Maguire
Cristiano Ronaldo
Scott McTominay
Fred
Victor Lindelöf
Aaron Wan-Bissaka
Jadon Sancho
Luke Shaw
Raphaël Varane
Paul Pogba
Mason Greenwood
Diogo Dalot
Alex Telles
Marcus Rashford
Nemanja Matić
Anthony Elanga
Edinson Cavani
Eric Bailly
Jesse Lingard
Anthony Martial
Phil Jones
Daniel James
Donny van de Beek
Juan Mata
Hannibal Mejbri
West Ham
https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats
Łukasz Fabiański
Declan Rice
Tomáš Souček
Michail Antonio
Jarrod Bowen
Pablo Fornals
Craig Dawson
Aaron Cresswell
Saïd Benrahma
Vladimír Coufal
Kurt Zouma
Manuel Lanzini
Ben Johnson
Angelo Ogbonna
Issa Diop
Nikola Vlašić
Arthur Masuaku
Ryan Fredericks
Mark Noble
Alphonse Areola
Andriy Yarmolenko
Harrison Ashby
Sonny Perkins
Daniel Chesters
Alex Král
Wolves
https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats
José Sá
Conor Coady
Max Kilman
Romain Saïss
João Moutinho
Rúben Neves
Raúl Jiménez
Nélson Semedo
Hwang Hee-chan
Fernando Marçal
Leander Dendoncker
Francisco Trincão
Daniel Podence
Rayan Aït Nouri
Adama Traoré
Jonny Castro
Fábio Silva
Willy Boly
Ki-Jana Hoever
Toti Gomes
Luke Cundle
Pedro Neto
Chiquinho
Chem Campbell
Morgan Gibbs-White
Leicester City
https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats
Kasper Schmeichel
Çağlar Söyüncü
Youri Tielemans
James Maddison
Harvey Barnes
Luke Thomas
Daniel Amartey
Wilfred Ndidi
Kiernan Dewsbury Hall
Jamie Vardy
Timothy Castagne
Ademola Lookman
Ricardo Pereira
Boubakary Soumaré
Jonny Evans
Kelechi Iheanacho
Marc Albrighton
Patson Daka
James Justin
Jannik Vestergaard
Nampalys Mendy
Ryan Bertrand
Hamza Choudhury
Ayoze Pérez
Wesley Fofana
Kasey McAteer
Brighton
https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats
Robert Sánchez
Marc Cucurella
Leandro Trossard
Joël Veltman
Neal Maupay
Lewis Dunk
Yves Bissouma
Pascal Groß
Jakub Moder
Adam Lallana
Alexis Mac Allister
Tariq Lamptey
Shane Duffy
Adam Webster
Solly March
Dan Burn
Danny Welbeck
Enock Mwepu
Steven Alzate
Moisés Caicedo
Aaron Connolly
Jason Steele
Jeremy Sarmiento
Taylor Richards
Evan Ferguson
Jürgen Locadia
Newcastle Utd
https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats
Allan Saint-Maximin
Joelinton
Fabian Schär
Joe Willock
Jonjo Shelvey
Martin Dúbravka
Jamaal Lascelles
Ryan Fraser
Miguel Almirón
Javier Manquillo
Matt Ritchie
Emil Krafth
Chris Wood
Callum Wilson
Jacob Murphy
Ciaran Clark
Isaac Hayden
Sean Longstaff
Dan Burn
Matt Targett
Karl Darlow
Bruno Guimarães
Federico Fernández
Freddie Woodman
Kieran Trippier
Jamal Lewis
Paul Dummett
Jeff Hendrick
Dwight Gayle
Brentford
https://fbref.com/en/squads/cd051869/Brentford-Stats
Pontus Jansson
Christian Nørgaard
Ethan Pinnock
Bryan Mbeumo
Rico Henry
Ivan Toney
Sergi Canós
Vitaly Janelt
David Raya
Kristoffer Ajer
Mathias Jensen
Álvaro Fernández
Frank Onyeka
Mads Roerslev
Yoane Wissa
Shandon Baptiste
Mathias Jørgensen
Christian Eriksen
Mads Bech Sørensen
Charlie Goode
Saman Ghoddos
Jonas Lössl
Dominic Thompson
Josh Dasilva
Marcus Forss
Mads Bidstrup
Tariqe Fosu
Finley Stevens
Southampton
https://fbref.com/en/squads/33c895d4/Southampton-Stats
James Ward-Prowse
Oriol Romeu
Mohammed Salisu
Jan Bednarek
Kyle Walker-Peters
Valentino Livramento
Che Adams
Mohamed Elyounoussi
Armando Broja
Fraser Forster
Romain Perraud
Nathan Redmond
Alex McCarthy
Adam Armstrong
Stuart Armstrong
Ibrahima Diallo
Lyanco
Jack Stephens
Nathan Tella
Moussa Djenepo
Theo Walcott
Yan Valery
Willy Caballero
William Smallbone
Shane Long
Crystal Palace
https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats
Tyrick Mitchell
Marc Guéhi
Conor Gallagher
Vicente Guaita
Joachim Andersen
Wilfried Zaha
Joel Ward
Cheikhou Kouyaté
Jordan Ayew
Jeffrey Schlupp
Odsonne Édouard
James McArthur
Christian Benteke
Michael Olise
Will Hughes
Jean-Philippe Mateta
Nathaniel Clyne
Luka Milivojević
James Tomkins
Jack Butland
Eberechi Eze
Jaïro Riedewald
Jesuran Rak Sakyi
Nathan Ferguson
Aston Villa
https://fbref.com/en/squads/8602292d/Aston-Villa-Stats
Matty Cash
Emiliano Martínez
Tyrone Mings
John McGinn
Ollie Watkins
Douglas Luiz
Ezri Konsa
Jacob Ramsey
Danny Ings
Emi Buendía
Matt Targett
Philippe Coutinho
Lucas Digne
Ashley Young
Marvelous Nakamba
Axel Tuanzebe
Leon Bailey
Calum Chambers
Kortney Hause
Anwar El Ghazi
Morgan Sanson
Carney Chukwuemeka
Bertrand Traoré
Jed Steer
Cameron Archer
Keinan Davis
Trézéguet
Tim Iroegbunam
Jaden Philogene Bidace
Wesley Moraes
Leeds United
https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats
Illan Meslier
Stuart Dallas
Raphael Dias Belloli
Jack Harrison
Daniel James
Luke Ayling
Diego Llorente
Rodrigo
Mateusz Klich
Pascal Struijk
Adam Forshaw
Liam Cooper
Junior Firpo
Robin Koch
Kalvin Phillips
Tyler Roberts
Jamie Shackleton
Patrick Bamford
Joe Gelhardt
Charlie Cresswell
Cody Drameh
Leo Fuhr Hjelde
Crysencio Summerville
Sam Greenwood
Lewis Bate
Kristoffer Klaesson
Hélder Costa
Liam McCarron
Stuart McKinstry
Everton
https://fbref.com/en/squads/d3fd31cc/Everton-Stats
Jordan Pickford
Michael Keane
Séamus Coleman
Allan
Ben Godfrey
Demarai Gray
Richarlison
Abdoulaye Doucouré
Anthony Gordon
Andros Townsend
Mason Holgate
Alex Iwobi
Lucas Digne
Dominic Calvert-Lewin
Jonjoe Kenny
Yerry Mina
Salomón Rondón
Vitaliy Mykolenko
André Gomes
Donny van de Beek
Fabian Delph
Jarrad Branthwaite
Asmir Begović
Tom Davies
Jean-Philippe Gbamin
Ellis Simms
Dele Alli
Lewis Dobbin
Tyler Onyango
Anwar El Ghazi
Cenk Tosun
Moise Kean
Burnley
https://fbref.com/en/squads/943e8050/Burnley-Stats
Nick Pope
James Tarkowski
Dwight McNeil
Josh Brownhill
Ashley Westwood
Charlie Taylor
Ben Mee
Matthew Lowton
Maxwel Cornet
Chris Wood
Aaron Lennon
Wout Weghorst
Jack Cork
Connor Roberts
Jóhann Berg Guðmundsson
Jay Rodriguez
Nathan Collins
Erik Pieters
Ashley Barnes
Matěj Vydra
Wayne Hennessey
Dale Stephens
Kevin Long
Watford
https://fbref.com/en/squads/2abfe087/Watford-Stats
Moussa Sissoko
Emmanuel Dennis
Craig Cathcart
Joshua King
Kiko Femenía

Ben Foster
Juraj Kucka
Ismaila Sarr
Tom Cleverley
William Troost-Ekong
Imran Louza
Samir Santos
Hassane Kamara
João Pedro
Cucho
Daniel Bachmann
Adam Masina
Christian Kabasele
Danny Rose
Jeremy Ngakia
Edo Kayembe
Francisco Sierralta
Ken Sema
Oghenekaro Etebo
Ozan Tufan
Nicolas Nkoulou
Samuel Kalu
Ashley Fletcher
Troy Deeney
Dan Gosling
Norwich City
https://fbref.com/en/squads/1c781004/Norwich-City-Stats
Teemu Pukki
Kenny McLean
Ben Gibson
Max Aarons
Grant Hanley
Tim Krul
Brandon Williams
Pierre Lees-Melou
Milot Rashica
Josh Sargent
Billy Gilmour
Mathias Normann
Ozan Kabak
Dimitris Giannoulis
Angus Gunn
Adam Idah
Lukas Rupp
Kieran Dowell
Przemysław Płacheta
Sam Byram
Todd Cantwell
Andrew Omobamidele
Jakob Sørensen
Christos Tzolis
Christoph Zimmermann
Jon Rowe
Bali Mumba

In [19]:
# get the player name matching dictionary
with open(path/'match_list.json') as f:
  match_list = json.load(f)

match_list

{'Fabinho': 'Fabio Henrique Tavares',
 'Alisson': 'Alisson Ramses Becker',
 'Joël Matip': 'Joel Matip',
 'Joe Gomez': 'Joseph Gomez',
 'Naby Keïta': 'Naby Keita',
 'Adrián': 'Adrián San Miguel del Castillo',
 'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
 'Allan': 'Allan Marques Loureiro',
 'Richarlison': 'Richarlison de Andrade',
 'Gylfi Sigurðsson': 'Gylfi Sigurdsson',
 'Séamus Coleman': 'Seamus Coleman',
 'André Gomes': 'André Filipe Tavares Gomes',
 'Bernard': 'Bernard Anício Caldeira Duarte',
 'Çağlar Söyüncü': 'Çaglar Söyüncü',
 'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
 'Fred': 'Frederico Rodrigues de Paula Santos',
 'Nemanja Matić': 'Nemanja Matic',
 'Alex Telles': 'Alex Nicolao Telles',
 'Pierre Højbjerg': 'Pierre-Emile Højbjerg',
 'Son Heung-min': 'Heung-Min Son',
 'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
 'Érik Lamela': 'Erik Lamela',
 'Dele Alli': 'Bamidele Alli',
 'Carlos Vinícius': 'Carlos Vinicius Alves Morais',
 'Ederson': 'Ederson Santana de Moraes',
 'Rodri': 'Rodrigo Hernandez',
 'Rúben Dias': 'Rúben Santos Gato Alves Dias',
 'João Cancelo': 'João Pedro Cavaco Cancelo',
 'İlkay Gündoğan': 'Ilkay Gündogan',
 'Gabriel Jesus': 'Gabriel Fernando de Jesus',
 'Ferrán Torres': 'Ferran Torres',
 'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
 'Fernandinho': 'Fernando Luiz Rosa',
 'Eric García': 'Eric Garcia',
 'Matty Cash': 'Matthew Cash',
 'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
 'Ezri Konsa': 'Ezri Konsa Ngoyo',
 'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
 'Ben Chilwell': 'Benjamin Chilwell',
 'Thiago Silva': 'Thiago Emiliano da Silva',
 'Mateo Kovačić': 'Mateo Kovacic',
 'Jorginho': 'Jorge Luiz Frello Filho',
 'Emerson Palmieri': 'Emerson Palmieri dos Santos',
 'Oriol Romeu': 'Oriol Romeu Vidal',
 'Dan Nlundulu': "Daniel N'Lundulu",
 'Łukasz Fabiański': 'Lukasz Fabianski',
 'Tomáš Souček': 'Tomas Soucek',
 'Vladimír Coufal': 'Vladimir Coufal',
 'Felipe Anderson': 'Felipe Anderson Pereira Gomes',
 'Rui Patrício': 'Rui Pedro dos Santos Patrício',
 'Pedro Neto': 'Pedro Lomba Neto',
 'Daniel Podence': 'Daniel Castelo Podence',
 'Nélson Semedo': 'Nélson Cabral Semedo',
 'Rúben Neves': 'Rúben Diogo da Silva Neves',
 'João Moutinho': 'João Filipe Iria Santos Moutinho',
 'Rayan Aït Nouri': 'Rayan Ait Nouri',
 'Fábio Silva': 'Fabio Silva',
 'Rúben Vinagre': 'Rúben Gonçalo Silva Nascimento Vinagre',
 'Vitinha': 'Vitor Ferreira',
 'Rodrigo': 'Rodrigo Moreno',
 'Pablo Hernández': 'Pablo Hernández Domínguez',
 'Ian Carlo Poveda': 'Ian Carlo Poveda-Ocampo',
 'Joelinton': 'Joelinton Cássio Apolinário de Lira',
 'Luka Milivojević': 'Luka Milivojevic',
 'Jaïro Riedewald': 'Jairo Riedewald',
 'Gabriel Dos Santos': 'Gabriel Magalhães',
 'Willian': 'Willian Borges Da Silva',
 'Dani Ceballos': 'Daniel Ceballos Fernández',
 'David Luiz': 'David Luiz Moreira Marinho',
 'Eddie Nketiah': 'Edward Nketiah',
 'Joe Willock': 'Joseph Willock',
 'Sead Kolašinac': 'Sead Kolasinac',
 'Martinelli': 'Gabriel Teodoro Martinelli Silva',
 'Solly March': 'Solomon March',
 'Bernardo': 'Bernardo Fernandes da Silva Junior',
 'Jóhann Berg Guðmundsson': 'Johann Berg Gudmundsson',
 'Matěj Vydra': 'Matej Vydra',
 'Andre-Frank Zambo Anguissa': 'André-Frank Zambo Anguissa',
 'Semi Ajayi': 'Oluwasemilogo Adesewo Ibidapo Ajayi',
 'Branislav Ivanović': 'Branislav Ivanovic',
 'Filip Krovinović': 'Filip Krovinovic',
 'Ahmed Hegazi': 'Ahmed El-Sayed Hegazi',
 'Harvey Elliot': 'Harvey Elliott',
 'Angeliño': 'Angelo Ogbonna',
 'Thomas Doyle': 'Tommy Doyle',
 'Diogo Dalot': 'José Diogo Dalot Teixeira',
 'Pedro': 'Pedro Rodríguez Ledesma',
 'Ricardo Pereira': 'Ricardo Domingos Barbosa Pereira',
 'Gedson Fernandes': 'Gedson Carvalho Fernandes',
 "Georges-Kévin N'Koudou": 'Georges-Kévin Nkoudou',
 'Jonny Castro': 'Jonathan Castro Otto',
 'Jesús Vallejo': 'Jesús Vallejo Lázaro',
 'Bruno Jordão': 'Bruno André Cavaco Jordao',
 'Mattéo Guendouzi': 'Matteo Guendouzi',
 'Richairo Živković': 'Richairo Zivkovic',
 'Danny Drinkwater': 'Daniel Drinkwater',
 'Martin Dúbravka': 'Martin Dubravka',
 'Yoshinori Mutō': 'Yoshinori Muto',
 'Ki Sung-yueng': 'Sung-yueng Ki',
 'Roberto': 'Roberto Jimenez Gago',
 'Javier Hernández': 'Javier Hernández Balcázar',
 'Frederic Guilbert': 'Frédéric Guilbert',
 'Björn Engels': 'Bjorn Engels',
 'Pepe Reina': 'José Reina',
 'Jota': 'José Ignacio Peleteiro Romallo',
 'Arnaut Groeneveld': 'Arnaut Danjuma Groeneveld',
 'Étienne Capoue': 'Etienne Capoue',
 'Kiko Femenía': 'Francisco Femenía Far',
 'Ismaila Sarr': 'Ismaila Sarr',
 'João Pedro': 'João Pedro Junqueira de Jesus',
 'Max Aarons': 'Max Aarons',
 'Emi Buendía': 'Emiliano Buendía Stati',
 'Mario Vrančić': 'Mario Vrancic',
 'Josip Drmić': 'Josip Drmic',
 'Ralf Fährmann': 'Ralf Fahrmann',
 'Danilo': 'Danilo Luiz da Silva',
 'Petr Čech': 'Petr Cech',
 'Idrissa Gana Gueye': 'Idrissa Gueye',
 'Marko Arnautović': 'Marko Arnautovic',
 'Xande Silva': 'Alexandre Nascimento Costa Silva',
 'Julián Speroni': 'Julian Speroni',
 'Kenedy': 'Robert Kenedy Nunes do Nascimento',
 'Joselu': 'Jose Luis Mato Sanmartín',
 'Asmir Begović': 'Asmir Begović',
 'Kayne Ramsey': 'Kayne Ramsay',
 'Bruno': 'Bruno Saltor Grau',
 'Junior Hoilett': 'David Junior Hoilett',
 'Greg Cunningham': 'Greg Cunninghamm',
 'Jazz Richards': 'Ashley Darel Jazz Richards',
 'Jean Seri': 'Jean Michael Seri',
 'Fabricio': 'Fabricio Agosto Ramírez',
 'Lazar Marković': 'Lazar Markovic',
 'Mathias Jørgensen': 'Mathias Jorgensen',
 'Steve Mounié': 'Steve Mounie',
 'Jon Gorenc Stanković': 'Jon Gorenc Stankovic',
 'Matty Daly': 'Matthew Daly',
 'Yaya Touré': 'Gnegneri Yaya Touré',
 'Brahim Díaz': 'Brahim Diaz',
 'Zlatan Ibrahimović': 'Zlatan Ibrahimovic',
 'Marko Grujić': 'Marko Grujic',
 'Charly Musonda Jr.': 'Charly Musonda',
 'Nikola Vlašić': 'Nikola Vlasic',
 'Aleksandar Dragović': 'Aleksandar Dragovic',
 'Eldin Jakupović': 'Eldin Jakupovic',
 'Rob Elliot': 'Robert Elliot',
 'Jesús Gámez': 'Jesús Gámez Duarte',
 'Massadio Haïdara': 'Massadio Haidara',
 'Lee Chung-yong': 'Chung-yong Lee',
 'Freddie Ladapo': 'Olayinka Fredrick Oladotun Ladapo',
 'João Mário': 'João Mário Naval Costa Eduardo',
 'José Fonte': 'Jose Fonte',
 'Younès Kaboul': 'Younes Kaboul',
 'Izzy Brown': 'Isaiah Brown',
 'Dušan Tadić': 'Dusan Tadic',
 'Àngel Rangel': 'Angel Rangel',
 'Badou Ndiaye': 'Papa Alioune Ndiaye',
 'Jesé': 'Jesé Rodríguez Ruiz',
 'Tom Edwards': 'Thomas Edwards',
 'Kostas Stafylidis': 'Konstantinos Stafylidis',
 'Lasse Sørensen': 'Lasse Sorenson',
 'Bojan Krkić': 'Bojan Krkic',
 'Allan Nyom': 'Allan-Roméo Nyom',
 'Ahmed Elmohamady': 'Ahmed El Mohamady',
 'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
 'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
 'Emile Smith-Rowe': 'Emile Smith Rowe',
 'Ivan Cavaleiro': 'Ivan Ricardo Neves Abreu Cavaleiro',
 'Bobby Reid': 'Bobby Decordova-Reid',
 'Ahmed El-Sayed Hegazi': 'Ahmed El-Sayed Hegazy',
 'Kiko Casilla': 'Francisco Casilla Cortés',
 'Willian José': 'Willian José Da Silva',
 'Kostas Tsimikas': 'Konstantinos Tsimikas',
 'Okay Yokuşlu': 'Okay Yokuslu',
 'Khanya Leshabela': 'Thakgalo Leshabela',
 'Jaden Philogene Bidace': 'Jaden Philogene-Bidace',
 'William Thomas Fish': 'William Fish',
 'David Raya': 'David Raya Martin',
 'Oghenekaro Etebo': 'Oghenekaro Peter Etebo',
 'Ismaïla Sarr': 'Ismaila Sarr',
 'Cucho': 'Juan Camilo Hernández Suárez',
 'Enoch Mwepu': 'Enock Mwepu',
 'Emiliano Buendía': 'Emiliano Buendía StatiJosé Malheiro de Sá',
 'José Sá': 'José Malheiro de Sá',
 'Francisco Trincão': 'Francisco Machado Mota de Castro Trincão',
 'Valentino Livramento': 'Tino Livramento',
 'Nuno Tavares': 'Nuno Varela Tavares',
 'Jesuran Rak Sakyi': 'Jesurun Rak-Sakyi',
 'Maximillian Aarons': 'Max Aarons',
 'Josh Sargent': 'Joshua Sargent',
 'Junior Firpo': 'Héctor Junior Firpo Adames',
 'Imran Louza': 'Imrân Louza',
 'Bryan': 'Bryan Gil Salvatierra',
 'Kiernan Dewsbury Hall': 'Kiernan Dewsbury-Hall',
 'Cristiano Ronaldo': 'Cristiano Ronaldo dos Santos Aveiro',
 'Emerson': 'Emerson Aparecido Leite de Souza Junior',
 'Mads Roerslev': 'Mads Roerslev Rasmussen',
 'Odsonne Édouard': 'Odsonne Edouard',
 'Hwang Hee-chan': 'Hee-Chan Hwang',
 'Asmir Begovic': 'Asmir Begović',
 'Caoimhín Kelleher': 'Caoimhin Kelleher',
 'Lyanco': 'Lyanco Evangelista Silveira Neves Vojnovic',
 'Przemysław Płacheta': 'Przemyslaw Placheta',
 'James Mcatee': 'James McAtee',
 'Jakob Sørensen': 'Jacob Sørensen',
 'Alex Král': 'Alex Kral',
 'Jon Rowe': 'Jonathan Rowe',
 'Toti Gomes': 'Toti António Gomes',
 'Philippe Coutinho': 'Philippe Coutinho Correia',
 'Vitaliy Mykolenko': 'Vitalii Mykolenko',
 'Samir Santos': 'Samir Caetano de Souza Santos',
 'Chiquinho': 'Francisco Jorge Tomás Oliveira',
 'Josh Dasilva': 'Pelenda Joshua Dasilva',
 'Bruno Guimarães': 'Bruno Guimarães Rodriguez Moura',
 'Kayky Chagas': 'Kayky da Silva Chagas',
 'Tariqe Fosu': 'Tariqe Fosu-Henry'}

In [20]:
team_list = {}
team_list['Brighton'] = 'Brighton and Hove Albion'
team_list['Leeds United'] = 'Leeds'
team_list['Manchester Utd'] = 'Manchester United'
team_list['Newcastle Utd'] = 'Newcastle United'
team_list['Norwich City'] = 'Norwich'
team_list['Sheffield Utd'] = 'Sheffield United'
team_list['Tottenham'] = 'Tottenham Hotspur'
team_list['West Brom'] = 'West Bromwich Albion'
team_list['West Ham'] = 'West Ham United'
team_list['Wolves'] = 'Wolverhampton Wanderers'

In [21]:
df_enhanced = df_enhanced.loc[df_enhanced[df_enhanced['round'].str[-2:] != 'on'].index]
df_enhanced = df_enhanced.loc[df_enhanced[df_enhanced['squad'] != 'CSKA Moscow'].index]

In [22]:
# replace non-matching names/teams and extract gw as integer
df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)
df_enhanced['squad'] = df_enhanced['squad'].replace(team_list)
df_enhanced['round'] = df_enhanced['round'].str[-2:].astype('int')

In [23]:
# remove duplicated (happens when players transferred within season)
df_enhanced = df_enhanced.drop_duplicates()

In [24]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9067,2021-2022,Jon Rowe,2022-03-10,Norwich,Premier League,30,0,0,8,0,...,0.0,0,0,7,7,100.0,8,0,0,Jonathan Rowe
9068,2021-2022,Jon Rowe,2022-03-13,Norwich,Premier League,29,2,1,15,6,...,0.0,0,0,6,9,66.7,13,2,3,Jonathan Rowe
9069,2021-2022,Jon Rowe,2022-04-02,Norwich,Premier League,31,0,0,8,8,...,0.0,0,0,1,4,25.0,6,0,1,Jonathan Rowe
9070,2021-2022,Jon Rowe,2022-04-16,Norwich,Premier League,33,0,0,6,4,...,0.0,0,0,2,3,66.7,5,0,1,Jonathan Rowe
9071,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [25]:
# create date field in same format as enhanced data
df_latest['date'] = df_latest['kickoff_time'].str[:10]

In [26]:
# check if any names aren't matching
enhanced_players = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['alt_name'].unique().tolist()
standard_players = df_latest['player'].unique().tolist()

unmatched_players = [x for x in enhanced_players if x not in standard_players]
unmatched_players

[]

In [27]:
# check if any teams aren't matching
enhanced_teams = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['squad'].unique().tolist()
standard_teams = df_latest['team'].unique().tolist()

unmatched_teams = [x for x in enhanced_teams if x not in standard_teams]
unmatched_teams

[]

In [28]:
# any additional corrections
# match_list['Tariqe Fosu'] = 'Tariqe Fosu-Henry'
# match_list['Josh Dasilva'] = 'Pelenda Joshua Dasilva'
# match_list['Bruno Guimarães'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Samir Santos'] = 'Samir Caetano de Souza Santos'
# match_list['Hwang Hee-chan'] = 'Hee-Chan Hwang'

# match_list['Sadio Man�'] = 'Sadio Mané'
# match_list['Jo�l Matip'] = 'Joel Matip'
# match_list['Thiago Alc�ntara'] = 'Thiago Alcántara do Nascimento'
# match_list['Naby Ke�ta'] = 'Naby Keita'
# match_list['Luis D�az'] = 'Luis Díaz'
# match_list['Jos� S�'] = 'José Malheiro de Sá'
# match_list['Romain Sa�ss'] = 'Romain Saïss'
# match_list['N�lson Semedo'] = 'Nélson Cabral Semedo'
# match_list['Ra�l Jim�nez'] = 'Raúl Jiménez'
# match_list['Jo�o Moutinho'] = 'João Filipe Iria Santos Moutinho'
# match_list['R�ben Neves'] = 'Rúben Diogo da Silva Neves'
# match_list['Rayan A�t Nouri'] = 'Rayan Ait Nouri'
# match_list['Fernando Mar�al'] = 'Fernando Marçal'
# match_list['Emiliano Mart�nez'] = 'Emiliano Martínez'
# match_list['Emi Buend�a'] = 'Emiliano Buendía Stati'
# match_list['Fabian Sch�r'] = 'Fabian Schär'
# match_list['Martin D�bravka'] = 'Martin Dubravka'
# match_list['Miguel Almir�n'] = 'Miguel Almirón'
# match_list['Bruno Guimar�es'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Kiko Femen�a'] = 'Francisco Femenía Far'

In [29]:
# replace additional non-matching names
# df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)

In [30]:
# make sure there are no non matches after update
# enhanced_teams = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['squad'].unique().tolist()
# standard_teams = df_latest['team'].unique().tolist()

# unmatched_teams = [x for x in enhanced_teams if x not in standard_teams]
# unmatched_teams

In [31]:
# if match list was updated then update the file
# json_file = json.dumps(match_list)
# f = open(path/"match_list.json","w")
# f.write(json_file)
# f.close()

In [32]:
# check there are no duplicates in the join fields for the enhanced data
assert(len(df_enhanced[df_enhanced.duplicated(subset=['alt_name', 'date'], keep=False)]) == 0)

In [33]:
df_latest[df_latest.duplicated(subset=['date','player','team'], keep=False)]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date]
Index: []

[0 rows x 36 columns]

In [34]:
# check there are no duplicates in the join fields for the standard data
assert(len(df_train[df_train.duplicated(subset=['date','player','team'])]) == 0)

In [35]:
# df_train[df_train.duplicated(subset=['date','player','team'])]

In [36]:
# join standard and enhanced dataframes
df_latest_further = df_latest.merge(df_enhanced.drop(['player', 'season', 'round'], axis=1), 
                                   left_on=['date', 'player', 'team'], 
                                   right_on=['date', 'alt_name', 'squad'], how='left')

In [37]:
# drop the alt name field and check the length of the standard
# dataframe has not increased
df_latest_further = df_latest_further.drop(['alt_name'], axis=1)
assert(len(df_latest_further) == len(df_latest_further))

In [38]:
# add crowds field
df_latest_further['crowds'] = 1

In [39]:
assert(sum(df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()) == 0)

In [40]:
df_latest_further[df_latest_further['minutes'] > 0][df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date, squad, comp, shots_total, shots_on_target, touches, pressures, tackles, interceptions, blocks, xg, npxg, xa, sca, gca, passes_completed, passes, passes_pct, carries, dribbles_completed, dribbles, crowds]
Index: []

[0 rows x 57 columns]

In [41]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9067,2021-2022,Jon Rowe,2022-03-10,Norwich,Premier League,30,0,0,8,0,...,0.0,0,0,7,7,100.0,8,0,0,Jonathan Rowe
9068,2021-2022,Jon Rowe,2022-03-13,Norwich,Premier League,29,2,1,15,6,...,0.0,0,0,6,9,66.7,13,2,3,Jonathan Rowe
9069,2021-2022,Jon Rowe,2022-04-02,Norwich,Premier League,31,0,0,8,8,...,0.0,0,0,1,4,25.0,6,0,1,Jonathan Rowe
9070,2021-2022,Jon Rowe,2022-04-16,Norwich,Premier League,33,0,0,6,4,...,0.0,0,0,2,3,66.7,5,0,1,Jonathan Rowe
9071,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [42]:
df_train_new = pd.concat([df_train, df_latest_further], ignore_index=True, axis=0, sort=False)

In [43]:
df_train_new[df_train_new['player'] == 'Harry Kane'].tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
132635,Harry Kane,29,4,90,Tottenham Hotspur,Brighton and Hove Albion,NaN,NaN,False,8,...,0.3,7.0,0.0,23.0,32.0,71.9,40.0,2.0,4.0,1
133347,Harry Kane,30,4,90,Tottenham Hotspur,West Ham United,NaN,NaN,True,13,...,0.7,6.0,2.0,26.0,42.0,61.9,47.0,3.0,3.0,1
133813,Harry Kane,31,4,90,Tottenham Hotspur,Newcastle United,NaN,NaN,True,4,...,0.9,7.0,2.0,16.0,25.0,64.0,27.0,1.0,2.0,1
134575,Harry Kane,32,4,90,Tottenham Hotspur,Aston Villa,NaN,NaN,False,10,...,0.6,5.0,3.0,15.0,18.0,83.3,24.0,3.0,6.0,1
135348,Harry Kane,33,4,90,Tottenham Hotspur,Brighton and Hove Albion,NaN,NaN,True,2,...,0.3,2,0,12,18,66.7,18,1,1,1

In [44]:
df_train_new.tail(10)

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
135897,Yves Bissouma,33,3,90,Brighton and Hove Albion,Tottenham Hotspur,NaN,NaN,False,2,...,0.0,2,0,65,69,94.2,54,2,2,1
135898,Yves Bissouma,33,3,0,Brighton and Hove Albion,Manchester City,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135899,Zach Awe,33,2,0,Arsenal,Southampton,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135900,Zach Awe,33,2,0,Arsenal,Chelsea,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135901,Zack Steffen,33,1,0,Manchester City,Brighton and Hove Albion,NaN,NaN,True,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135902,Zak Swanson,33,2,0,Arsenal,Southampton,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135903,Zak Swanson,33,2,0,Arsenal,Chelsea,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135904,Álvaro Fernández,33,1,0,Brentford,Watford,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
135905,Çaglar Söyüncü,33,2,90,Leicester City,Newcastle United,NaN,NaN,False,1,...,0.0,0,0,71,78,91.0,63,0,0,1
135906,Çaglar Söyüncü,33,2,0,Leicester City,Everton,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [45]:
df_latest_further.shape

(854, 57)

In [46]:
df_train_new.shape

(135907, 59)

In [47]:
# save latest training set to csv
# overwrite existing one
df_train_new.to_csv(path/'train_v8.csv')

In [48]:
# get fixtures
fixtures = pd.read_csv(path/'2021-22/fixtures.csv')
team_dict = teams[['team_2122', 'team']].dropna().set_index('team_2122').to_dict()['team']

fixtures['home_team'] = fixtures['team_h'].replace(team_dict)
fixtures['away_team'] = fixtures['team_a'].replace(team_dict)
fixtures = fixtures[['home_team', 'away_team', 'kickoff_time', 'event']]
fixtures = fixtures.rename(columns={'event':'gw'})


# use these two lines if updating play_proba later in week
# current_gw = last_gw
# df_train_new = pd.read_csv(path/'train_v7.csv', index_col=0, dtype={'season':str,
#                                                                     'comp':str,
#                                                                     'squad':str})

# set starting gameweek (where are we right now in the season)
current_gw = last_gw + 1
fixtures = fixtures[fixtures['gw'] >= current_gw].sort_values(by=['gw'])
fixtures['match_no'] = np.arange(fixtures.shape[0])

In [49]:
fixtures.head(50)

,home_team,away_team,kickoff_time,gw,match_no
323,Arsenal,Manchester United,2022-04-23T11:30:00Z,34.0,0
324,Leicester City,Aston Villa,2022-04-23T14:00:00Z,34.0,1
325,Manchester City,Watford,2022-04-23T14:00:00Z,34.0,2
326,Norwich,Newcastle United,2022-04-23T14:00:00Z,34.0,3
327,Brentford,Tottenham Hotspur,2022-04-23T16:30:00Z,34.0,4
328,Brighton and Hove Albion,Southampton,2022-04-24T13:00:00Z,34.0,5
329,Burnley,Wolverhampton Wanderers,2022-04-24T13:00:00Z,34.0,6
330,Chelsea,West Ham United,2022-04-24T13:00:00Z,34.0,7
331,Liverpool,Everton,2022-04-24T15:30:00Z,34.0,8
332,Crystal Palace,Leeds,2022-04-25T19:00:00Z,34.0,9
333,Manchester United,Chelsea,2022-04-28T18:45:00Z,34.0,10
343,Manchester United,Brentford,2022-05-02T19:00:00Z,35.0,11
342,West Ham United,Arsenal,2022-05-01T15:30:00Z,35.0,12
341,Tottenham Hotspur,Leicester City,2022-05-01T13:00:00Z,35.0,13
340,Everton,Chelsea,2022-05-01T13:00:00Z,35.0,14
339,Leeds,Manchester City,2022-04-30T16:30:00Z,35.0,15
336,Southampton,Crystal Palace,2022-04-30T14:00:00Z,35.0,16
337,Watford,Burnley,2022-04-30T14:00:00Z,35.0,17
335,Aston Villa,Norwich,2022-04-30T14:00:00Z,35.0,18
334,Newcastle United,Liverpool,2022-04-30T11:30:00Z,35.0,19
338,Wolverhampton Wanderers,Brighton and Hove Albion,2022-04-30T14:00:00Z,35.0,20
353,Manchester City,Newcastle United,2022-05-08T15:30:00Z,36.0,21
358,Tottenham Hotspur,Arsenal,2022-05-12T18:45:00Z,36.0,22
357,Watford,Everton,2022-05-11T18:45:00Z,36.0,23
356,Leicester City,Norwich,2022-05-11T18:45:00Z,36.0,24
355,Leeds,Chelsea,2022-05-11T18:30:00Z,36.0,25
354,Aston Villa,Liverpool,2022-05-10T19:00:00Z,36.0,26
352,Norwich,West Ham United,2022-05-08T13:00:00Z,36.0,27
351,Leicester City,Everton,2022-05-08T13:00:00Z,36.0,28
350,Arsenal,Leeds,2022-05-08T13:00:00Z,36.0,29
349,Liverpool,Tottenham Hotspur,2022-05-07T18:45:00Z,36.0,30
348,Brighton and Hove Albion,Manchester United,2022-05-07T16:30:00Z,36.0,31
347,Crystal Palace,Watford,2022-05-07T14:00:00Z,36.0,32
346,Chelsea,Wolverhampton Wanderers,2022-05-07T14:00:00Z,36.0,33
345,Burnley,Aston Villa,2022-05-07T14:00:00Z,36.0,34
344,Brentford,Southampton,2022-05-07T14:00:00Z,36.0,35
369,Chelsea,Leicester City,2022-05-19T19:00:00Z,37.0,36
368,Aston Villa,Burnley,2022-05-19T19:00:00Z,37.0,37
367,Everton,Crystal Palace,2022-05-19T18:45:00Z,37.0,38
366,Newcastle United,Arsenal,2022-05-16T19:00:00Z,37.0,39
364,Wolverhampton Wanderers,Norwich,2022-05-15T13:00:00Z,37.0,40
365,West Ham United,Manchester City,2022-05-15T15:30:00Z,37.0,41
362,Leeds,Brighton and Hove Albion,2022-05-15T13:00:00Z,37.0,42
361,Everton,Brentford,2022-05-15T13:00:00Z,37.0,43
360,Aston Villa,Crystal Palace,2022-05-15T13:00:00Z,37.0,44
359,Tottenham Hotspur,Burnley,2022-05-15T11:00:00Z,37.0,45
363,Watford,Leicester City,2022-05-15T13:00:00Z,37.0,46
378,Manchester City,Aston Villa,2022-05-22T15:00:00Z,38.0,47
370,Arsenal,Everton,2022-05-22T15:00:00Z,38.0,48
371,Brentford,Leeds,2022-05-22T15:00:00Z,38.0,49

In [50]:
# add universal team codes for home and away teams
fixtures = fixtures.merge(teams, left_on='home_team', right_on='team', how='left')
fixtures = fixtures.merge(teams, left_on='away_team', right_on='team', how='left')
fixtures = fixtures[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 'team_code_x', 'team_code_y']]
fixtures.rename(index=str,
                columns={'team_code_x':'home_team_code',
                         'team_code_y':'away_team_code'},
                inplace=True)

In [51]:
fixtures.head()

,gw,match_no,home_team,away_team,kickoff_time,home_team_code,away_team_code
0,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,3,1
1,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,13,7
2,34.0,2,Manchester City,Watford,2022-04-23T14:00:00Z,43,57
3,34.0,3,Norwich,Newcastle United,2022-04-23T14:00:00Z,45,4
4,34.0,4,Brentford,Tottenham Hotspur,2022-04-23T16:30:00Z,94,6

In [52]:
# all_players.replace(to_replace='None', value=1, inplace=True)

In [53]:
all_players[all_players['play_proba_2122'] == '0']

,full_name,play_proba_2122,position_2122,id_2122,cost_2122,team_2122,web_name_2122
1,Rúnar Alex Rúnarsson,0,1,2,40,3,Rúnarsson
2,Willian Borges Da Silva,0,3,3,63,3,Willian
3,Pierre-Emerick Aubameyang,0,4,4,96,3,Aubameyang
7,Pablo Marí,0,2,8,42,3,Marí
8,Héctor Bellerín,0,2,9,48,3,Bellerín
...,...,...,...,...,...,...,...
716,Christian Marques,0,2,549,40,39,Marques
718,Louie Moulden,0,1,611,40,39,Moulden
721,Bruno André Cavaco Jordão,0,3,661,45,39,Jordão
723,Dion Sanderson,0,2,686,40,39,Sanderson
724,Ryan Giles,0,3,687,45,39,Giles

In [54]:
# join home team to all players for current season
home_df = fixtures.merge(all_players, 
               left_on='home_team_code', 
               right_on='team_2122', 
               how='left')

# pull out the required fields and rename columns
home_df = home_df[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 
                   'full_name', 'position_2122', 'cost_2122', 'play_proba_2122', 
                   'web_name_2122']]
home_df.rename(index=str, 
               columns={'home_team':'team',
                        'away_team':'opponent_team',
                        'full_name':'player',
                        'position_2122':'position',
                        'cost_2122':'price',
                        'play_proba_2122':'play_proba',
                        'web_name_2122':'short_name'},
              inplace=True)

# add home flag
home_df['was_home'] = True

In [55]:
# join away team to all players for current season
away_df = fixtures.merge(all_players, 
               left_on='away_team_code', 
               right_on='team_2122', 
               how='left')

# pull out the required fields and rename columns
away_df = away_df[['gw',  'match_no', 'away_team', 'home_team', 'kickoff_time', 
                   'full_name', 'position_2122', 'cost_2122', 'play_proba_2122', 
                   'web_name_2122']]
away_df.rename(index=str, 
               columns={'away_team':'team',
                        'home_team':'opponent_team',
                        'full_name':'player',
                        'position_2122':'position',
                        'cost_2122':'price',
                        'play_proba_2122':'play_proba',
                        'web_name_2122':'short_name'},
              inplace=True)

# add home flag
away_df['was_home'] = False

In [56]:
# look at away players
away_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,34.0,0,Manchester United,Arsenal,2022-04-23T11:30:00Z,Edinson Cavani,4,84,0,Cavani,False
1,34.0,0,Manchester United,Arsenal,2022-04-23T11:30:00Z,David de Gea,1,51,None,de Gea,False
2,34.0,0,Manchester United,Arsenal,2022-04-23T11:30:00Z,Nemanja Matic,3,43,100,Matic,False
3,34.0,0,Manchester United,Arsenal,2022-04-23T11:30:00Z,Paul Pogba,3,74,25,Pogba,False
4,34.0,0,Manchester United,Arsenal,2022-04-23T11:30:00Z,Harry Maguire,2,54,100,Maguire,False

In [57]:
# look at home players
home_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Bernd Leno,1,45,100,Leno,True
1,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Rúnar Alex Rúnarsson,1,40,0,Rúnarsson,True
2,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Willian Borges Da Silva,3,63,0,Willian,True
3,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Pierre-Emerick Aubameyang,4,96,0,Aubameyang,True
4,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Cédric Soares,2,42,100,Cédric,True

In [58]:
# # calculate average minutes over last 5 gameweeks
# # first get last 5 gameweeks in current season
# recent_mins = df_train_new[(df_train_new['gw'] >= current_gw - 5) & 
#                            (df_train_new['season'] == season_names[0])][['player', 'minutes', 'play_proba']]

# # recent_mins = df_train_new[((df_train_new['gw'] >= 40 - 5) & 
# #                            (df_train_new['season'] == '1920')) | 
# #                            ((df_train_new['gw'] >= 1) & 
# #                            (df_train_new['season'] == '2021'))][['player', 'minutes', 'play_proba']]

# # exclude weeks where the player had an injury designation (i.e. keep where play_proba is 1)
# recent_mins = recent_mins[recent_mins['play_proba'] == 1]

# len(recent_mins)

# # average for each player
# recent_mins = recent_mins.groupby(['player'])['minutes'].mean().to_dict()

# recent_mins

In [59]:
# concatenate home and away players
remaining_season_df = home_df.append(away_df).reset_index(drop=True)

# add home and away team market values
remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2122'],
                                                left_on='team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2122'],
                                                left_on='opponent_team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df.rename(index=str, 
                           columns={'relative_market_value_x':'relative_market_value_team',
                                    'relative_market_value_y':'relative_market_value_opponent_team'},
                           inplace=True)

# add season name
remaining_season_df['season'] = season_names[0]

# divide cost by 10 for actual cost
remaining_season_df['price'] = remaining_season_df['price']/10

# set availability probability
# 0 = 0% chance, 25 = 25% chance, etc
# 'None' or '100' = 100% chance
remaining_season_df.loc[remaining_season_df['play_proba'] == 'None', 'play_proba'] = 100
remaining_season_df['play_proba'] = remaining_season_df['play_proba'].astype('float') / 100

# cast position to integer
remaining_season_df['position'] = remaining_season_df['position'].astype(int)

# # add minutes based on last five fixtures
# remaining_season_df['minutes'] = remaining_season_df['player'].map(recent_mins)
# remaining_season_df['minutes'].fillna(0, inplace=True)

# # multiply minutes by play probability
# remaining_season_df['minutes'] = remaining_season_df['minutes'] * remaining_season_df['play_proba']

In [60]:
remaining_season_df.head(50)

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home,relative_market_value_team,relative_market_value_opponent_team,season
0,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Bernd Leno,1,4.5,1.0,Leno,True,NaN,NaN,2122
1,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Rúnar Alex Rúnarsson,1,4.0,0.0,Rúnarsson,True,NaN,NaN,2122
2,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Willian Borges Da Silva,3,6.3,0.0,Willian,True,NaN,NaN,2122
3,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Pierre-Emerick Aubameyang,4,9.6,0.0,Aubameyang,True,NaN,NaN,2122
4,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Cédric Soares,2,4.2,1.0,Cédric,True,NaN,NaN,2122
5,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Alexandre Lacazette,4,8.3,1.0,Lacazette,True,NaN,NaN,2122
6,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Granit Xhaka,3,4.8,1.0,Xhaka,True,NaN,NaN,2122
7,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Pablo Marí,2,4.2,0.0,Marí,True,NaN,NaN,2122
8,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Héctor Bellerín,2,4.8,0.0,Bellerín,True,NaN,NaN,2122
9,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Sead Kolasinac,2,4.2,0.0,Kolasinac,True,NaN,NaN,2122
10,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Mohamed Naser El Sayed Elneny,3,4.4,1.0,Elneny,True,NaN,NaN,2122
11,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Ainsley Maitland-Niles,3,5.2,0.0,Maitland-Niles,True,NaN,NaN,2122
12,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Rob Holding,2,4.1,1.0,Holding,True,NaN,NaN,2122
13,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Thomas Partey,3,5.0,0.0,Partey,True,NaN,NaN,2122
14,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Kieran Tierney,2,5.0,0.0,Tierney,True,NaN,NaN,2122
15,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Nicolas Pépé,3,6.9,1.0,Pépé,True,NaN,NaN,2122
16,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Lucas Torreira,3,4.5,0.0,Torreira,True,NaN,NaN,2122
17,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Edward Nketiah,4,5.4,1.0,Nketiah,True,NaN,NaN,2122
18,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Emile Smith Rowe,3,5.7,1.0,Smith Rowe,True,NaN,NaN,2122
19,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Bukayo Saka,3,6.8,1.0,Saka,True,NaN,NaN,2122
20,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Gabriel Magalhães,2,5.4,1.0,Gabriel,True,NaN,NaN,2122
21,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Konstantinos Mavropanos,2,4.5,0.0,Mavropanos,True,NaN,NaN,2122
22,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Mattéo Guendouzi,3,4.5,0.0,Guendouzi,True,NaN,NaN,2122
23,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Gabriel Teodoro Martinelli Silva,3,5.3,1.0,Martinelli,True,NaN,NaN,2122
24,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,William Saliba,2,4.5,0.0,Saliba,True,NaN,NaN,2122
25,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Ben White,2,4.6,1.0,White,True,NaN,NaN,2122
26,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Nuno Varela Tavares,2,4.3,1.0,Tavares,True,NaN,NaN,2122
27,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Albert Sambi Lokonga,3,4.8,1.0,Sambi Lokonga,True,NaN,NaN,2122
28,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Folarin Balogun,4,4.7,0.0,Balogun,True,NaN,NaN,2122
29,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Reiss Nelson,3,5.0,0.0,Nelson,True,NaN,NaN,2122
30,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Karl Hein,1,4.0,0.0,Hein,True,NaN,NaN,2122
31,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Martin Ødegaard,3,5.6,1.0,Ødegaard,True,NaN,NaN,2122
32,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Aaron Ramsdale,1,5.1,1.0,Ramsdale,True,NaN,NaN,2122
33,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Arthur Okonkwo,1,3.9,1.0,Okonkwo,True,NaN,NaN,2122
34,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Takehiro Tomiyasu,2,4.5,0.5,Tomiyasu,True,NaN,NaN,2122
35,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Charlie Patino,3,4.5,1.0,Patino,True,NaN,NaN,2122
36,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Omari Hutchinson,3,4.5,1.0,Hutchinson,True,NaN,NaN,2122
37,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Salah-Eddine Oulad M'hand,3,4.5,1.0,Oulad M'hand,True,NaN,NaN,2122
38,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Mika Biereth,4,4.5,1.0,Biereth,True,NaN,NaN,2122
39,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Ryan Alebiosu,2,4.0,0.0,Alebiosu,True,NaN,NaN,2122
40,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Zach Awe,2,4.0,1.0,Awe,True,NaN,NaN,2122
41,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Zak Swanson,2,4.0,1.0,Swanson,True,NaN,NaN,2122
42,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Mazeed Ogungbo,2,4.0,1.0,Ogungbo,True,NaN,NaN,2122
43,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Marcelo Flores,3,4.5,1.0,Flores,True,NaN,NaN,2122
44,34.0,0,Arsenal,Manchester United,2022-04-23T11:30:00Z,Miguel Azeez,3,4.5,1.0,Azeez,True,NaN,NaN,2122
45,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,Kasper Schmeichel,1,4.9,1.0,Schmeichel,True,NaN,NaN,2122
46,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,Jonny Evans,2,5.4,1.0,Evans,True,NaN,NaN,2122
47,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,Marc Albrighton,3,5.2,1.0,Albrighton,True,NaN,NaN,2122
48,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,Nampalys Mendy,3,4.3,1.0,Mendy,True,NaN,NaN,2122
49,34.0,1,Leicester City,Aston Villa,2022-04-23T14:00:00Z,Danny Ward,1,4.0,0.0,Ward,True,NaN,NaN,2122

In [61]:
# save latest prediction set to csv
remaining_season_df.to_csv(path/'remaining_season.csv')