In [1]:
# import required libriaries
from pathlib import Path
import json

from fpl_predictor.util import *

In [2]:
# path to data directory
#path = Path('/home/jupyter/fpl-prediction/data')
path = Path('./fpl_predictor/data')

In [3]:
# read in latest training set
df_train = pd.read_csv(path/'train_v8.csv', index_col=0, 
                       dtype={'season':str,
                              'comp':str,
                              'squad':str})

# path to current season
season_paths = [path/'2022-23']

# name for current season
season_names = ['2223']

# team codes
teams = pd.read_csv(path/'teams.csv')

# latest remaining season dataset, for latest week's play_proba values
remaining_season = pd.read_csv(path/'remaining_season.csv', index_col=0)

# create players dataset
all_players = build_players(path, season_paths, season_names, teams)

# 2019-20 market value
# table was in slightly different position for 2019-20 season
# should check that 2019-20 season values remain the same once season starts
teams_mv = build_season_mv('2223', 11, range(13,33))

In [67]:
# all_players#[all_players['full_name'] == 'Ben Davies']

In [68]:
# df_train = df_train.iloc[:-686]

In [4]:
# find the latest gameweek
last_gw = df_train['gw'][df_train['season'] == season_names[0]].max()

if np.isnan(last_gw): 
    last_gw = 1 
else: 
    last_gw = last_gw + 1
    
last_gw

1

In [70]:
# build training set for latest gameweek
df_latest = build_season(season_paths[0], season_names[0], all_players, teams, teams_mv, [last_gw])

In [71]:
df_latest.drop_duplicates(inplace=True)

In [72]:
# df_latest[df_latest['player'] == 'Chris Wood']
# lucas digne
# chris wood

In [73]:
last_play_proba = remaining_season[remaining_season['gw'] == last_gw][['player', 'team', 'play_proba']]

In [74]:
last_play_proba.head()

              player               team  play_proba
0         Ben Davies  Tottenham Hotspur         1.0
1           Joe Hart  Tottenham Hotspur         0.0
2        Hugo Lloris  Tottenham Hotspur         1.0
3  Toby Alderweireld  Tottenham Hotspur         0.0
4        Erik Lamela  Tottenham Hotspur         0.0

In [75]:
# add latest week's play_proba for each player
df_latest = df_latest.merge(last_play_proba, on=['player', 'team'], how='left')

In [76]:
df_latest.drop_duplicates(inplace=True)

In [77]:
df_train.drop_duplicates(inplace=True)

In [78]:
if last_gw==1:
    df_latest['relative_market_value_team_season'] = df_latest['relative_market_value_team']
    df_latest['relative_market_value_opponent_team_season'] = df_latest['relative_market_value_opponent_team']

In [16]:
# for when you're doing the season value properly
# relative_market_value_season = train_df[train_df['season'] == '2021'][['team', 'relative_market_value_team']].groupby(['team']).first()
# relative_market_value_season = relative_market_value_season.rename(columns={'relative_market_value_team': 'season_value'})
# relative_market_value_season

In [17]:
# now get futher stats from fbref
# standard stats
features = ['squad', 'comp', 'round', 'shots_total', 'shots_on_target', 'touches', 'pressures',
            'tackles', 'interceptions', 'blocks', 'xg', 'npxg', 'xa', 'sca', 
            'gca', 'passes_completed', 'passes', 'passes_pct',  'carries', 
            'dribbles_completed', 'dribbles']

In [18]:
# url for the premier league
url_base = 'https://fbref.com'
pl_history_page = '/en/comps/9/history/Premier-League-Seasons'
url = url_base + pl_history_page

# scrape the history table to get latest season
pl_history_table = get_table(url)
pl_history_urls = get_urls(['season'], 'season', pl_history_table, url_base)
season_urls = pl_history_urls[0:1]

df_enhanced = get_stats(features, season_urls, url_base)

2021-2022
https://fbref.com/en/comps/9/Premier-League-Stats
Manchester City
https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats
Ederson
João Cancelo
Rodri
Bernardo Silva
Aymeric Laporte
Rúben Dias
Kevin De Bruyne
Raheem Sterling
Phil Foden
Jack Grealish
İlkay Gündoğan
Gabriel Jesus
Kyle Walker
Riyad Mahrez
John Stones
Oleksandr Zinchenko
Nathan Aké
Fernandinho
Ferrán Torres
Cole Palmer
Zack Steffen
Benjamin Mendy
James Mcatee
Liam Delap
Kayky Chagas
CJ Egan-Riley
Liverpool
https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
Alisson
Virgil van Dijk
Trent Alexander-Arnold
Sadio Mané
Mohamed Salah
Joël Matip
Jordan Henderson
Andrew Robertson
Fabinho
Diogo Jota
Thiago Alcántara
Naby Keïta
Roberto Firmino
Ibrahima Konaté
Luis Díaz
Curtis Jones
Kostas Tsimikas
James Milner
Alex Oxlade-Chamberlain
Harvey Elliott
Joe Gomez
Caoimhín Kelleher
Takumi Minamino
Tyler Morton
Divock Origi
Kaide Gordon
Neco Williams
Chelsea
https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats
Edouard Mendy
Antonio Rüdiger
Thiago Silva
Mason Mount
Jorginho
Marcos Alonso
César Azpilicueta
Reece James
Kai Havertz
N'Golo Kanté
Andreas Christensen
Trevoh Chalobah
Romelu Lukaku
Mateo Kovačić
Timo Werner
Ruben Loftus-Cheek
Christian Pulisic
Hakim Ziyech
Callum Hudson-Odoi
Ben Chilwell
Malang Sarr
Saúl Ñíguez
Kepa Arrizabalaga
Ross Barkley
Emerson Palmieri
Tottenham
https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats
Hugo Lloris
Harry Kane
Pierre Højbjerg
Eric Dier
Son Heung-min
Ben Davies
Emerson
Sergio Reguilón
Cristian Romero
Lucas Moura
Davinson Sánchez
Rodrigo Bentancur
Oliver Skipp
Dejan Kulusevski
Ryan Sessegnon
Japhet Tanganga
Harry Winks
Matt Doherty
Dele Alli
Tanguy Ndombele
Steven Bergwijn
Giovani Lo Celso
Bryan
Joe Rodon
Dane Scarlett
Arsenal
https://fbref.com/en/squads/18bb7c10/Arsenal-Stats
Bukayo Saka
Gabriel Dos Santos
Aaron Ramsdale
Ben White
Martin Ødegaard
Granit Xhaka
Thomas Partey
Kieran Tierney
Emile Smith Rowe
Martinelli
Alexandre Lacazette
Takehiro Tomiyasu
Cédric Soares
Albert Sambi Lokonga
Nuno Tavares
Pierre-Emerick Aubameyang
Rob Holding
Eddie Nketiah
Mohamed Elneny
Nicolas Pépé
Bernd Leno
Ainsley Maitland-Niles
Pablo Marí
Calum Chambers
Sead Kolašinac
Folarin Balogun
Reiss Nelson
Manchester Utd
https://fbref.com/en/squads/19538871/Manchester-United-Stats
David de Gea
Bruno Fernandes
Cristiano Ronaldo
Harry Maguire
Scott McTominay
Backing off 0.2 seconds afters 1 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/d93c2511/matchlogs/2021-2022/summary/Scott-McTominay-Match-Logs',) and kwargs {}
Backing off 0.0 seconds afters 2 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/d93c2511/matchlogs/2021-2022/summary/Scott-McTominay-Match-Logs',) and kwargs {}
Victor Lindelöf
Fred
Backing off 0.7 seconds afters 1 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/b853e0ad/matchlogs/2021-2022/summary/Fred-Match-Logs',) and kwargs {}
Backing off 1.0 seconds afters 2 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/b853e0ad/matchlogs/2021-2022/summary/Fred-Match-Logs',) and kwargs {}
Backing off 0.7 seconds afters 3 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/b853e0ad/matchlogs/2021-2022/summary/Fred-Match-Logs',) and kwargs {}
Backing off 0.2 seconds afters 4 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/b853e0ad/matchlogs/2021-2022/summary/Fred-Match-Logs',) and kwargs {}
Backing off 4.8 seconds afters 5 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/b853e0ad/matchlogs/2021-2022/summary/Fred-Match-Logs',) and kwargs {}
Jadon Sancho
Raphaël Varane
Aaron Wan-Bissaka
Luke Shaw
Diogo Dalot
Alex Telles
Nemanja Matić
Paul Pogba
Mason Greenwood
Marcus Rashford
Anthony Elanga
Edinson Cavani
Eric Bailly
Jesse Lingard
Anthony Martial
Juan Mata
Phil Jones
Daniel James
Donny van de Beek
Hannibal Mejbri
Alejandro Garnacho
West Ham
https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats
Łukasz Fabiański
Declan Rice
Tomáš Souček
Jarrod Bowen
Michail Antonio
Pablo Fornals
Aaron Cresswell
Craig Dawson
Saïd Benrahma
Vladimír Coufal
Kurt Zouma
Manuel Lanzini
Ben Johnson
Angelo Ogbonna
Issa Diop
Arthur Masuaku
Nikola Vlašić
Mark Noble
Ryan Fredericks
Andriy Yarmolenko
Alphonse Areola
Harrison Ashby
Sonny Perkins
Daniel Chesters
Alex Král
Wolves
https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats
Conor Coady
José Sá
João Moutinho
Romain Saïss
Max Kilman
Rúben Neves
Raúl Jiménez
Nélson Semedo
Leander Dendoncker
Hwang Hee-chan
Rayan Aït Nouri
Fernando Marçal
Francisco Trincão
Daniel Podence
Adama Traoré
Jonny Castro
Willy Boly
Fábio Silva
Pedro Neto
Ki-Jana Hoever
Toti Gomes
Luke Cundle
Chiquinho
John Ruddy
Chem Campbell
Morgan Gibbs-White
Leicester City
https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats
Kasper Schmeichel
Youri Tielemans
Çağlar Söyüncü
James Maddison
Daniel Amartey
Harvey Barnes
Kiernan Dewsbury Hall
Timothy Castagne
Luke Thomas
Jamie Vardy
Wilfred Ndidi
Ademola Lookman
Jonny Evans
Kelechi Iheanacho
Patson Daka
Ricardo Pereira
Boubakary Soumaré
Marc Albrighton
Nampalys Mendy
James Justin
Jannik Vestergaard
Wesley Fofana
Ayoze Pérez
Ryan Bertrand
Hamza Choudhury
Danny Ward
Lewis Brunt
Kasey McAteer
Brighton
https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats
Robert Sánchez
Marc Cucurella
Leandro Trossard
Joël Veltman
Lewis Dunk
Neal Maupay
Yves Bissouma
Pascal Groß
Alexis Mac Allister
Jakub Moder
Adam Lallana
Solly March
Tariq Lamptey
Shane Duffy
Adam Webster
Danny Welbeck
Dan Burn
Enock Mwepu
Moisés Caicedo
Steven Alzate
Aaron Connolly
Jason Steele
Jeremy Sarmiento
Taylor Richards
Evan Ferguson
Jürgen Locadia
Brentford
https://fbref.com/en/squads/cd051869/Brentford-Stats
Pontus Jansson
Christian Nørgaard
Bryan Mbeumo
Rico Henry
Ethan Pinnock
Ivan Toney
Vitaly Janelt
Sergi Canós
David Raya
Kristoffer Ajer
Mathias Jensen
Mads Roerslev
Álvaro Fernández
Frank Onyeka
Yoane Wissa
Shandon Baptiste
Christian Eriksen
Mads Bech Sørensen
Mathias Jørgensen
Saman Ghoddos
Charlie Goode
Josh Dasilva
Jonas Lössl
Dominic Thompson
Marcus Forss
Mads Bidstrup
Backing off 0.0 seconds afters 1 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/407db0d5/matchlogs/2021-2022/summary/Mads-Bidstrup-Match-Logs',) and kwargs {}
Tariqe Fosu
Finley Stevens
Backing off 1.0 seconds afters 1 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/7e003182/matchlogs/2021-2022/summary/Finley-Stevens-Match-Logs',) and kwargs {}
Backing off 1.8 seconds afters 2 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/7e003182/matchlogs/2021-2022/summary/Finley-Stevens-Match-Logs',) and kwargs {}
Backing off 3.8 seconds afters 3 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/7e003182/matchlogs/2021-2022/summary/Finley-Stevens-Match-Logs',) and kwargs {}
Backing off 2.2 seconds afters 4 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/7e003182/matchlogs/2021-2022/summary/Finley-Stevens-Match-Logs',) and kwargs {}
Backing off 13.5 seconds afters 5 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/7e003182/matchlogs/2021-2022/summary/Finley-Stevens-Match-Logs',) and kwargs {}
Nathan Young-Coombes
Newcastle Utd
https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats
Allan Saint-Maximin
Joelinton
Martin Dúbravka
Fabian Schär
Joe Willock
Jonjo Shelvey
Jamaal Lascelles
Emil Krafth
Miguel Almirón
Ryan Fraser
Dan Burn
Matt Targett
Chris Wood
Callum Wilson
Javier Manquillo
Sean Longstaff
Matt Ritchie
Jacob Murphy
Ciaran Clark
Isaac Hayden
Bruno Guimarães
Karl Darlow
Federico Fernández
Freddie Woodman
Kieran Trippier
Jamal Lewis

Paul Dummett
Jeff Hendrick
Dwight Gayle
Crystal Palace
https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats
Marc Guéhi
Tyrick Mitchell
Conor Gallagher
Joachim Andersen
Wilfried Zaha
Vicente Guaita
Joel Ward
Jordan Ayew
Cheikhou Kouyaté
Jeffrey Schlupp
Odsonne Édouard
James McArthur
Nathaniel Clyne
Jean-Philippe Mateta
Michael Olise
Will Hughes
Christian Benteke
Luka Milivojević
Jack Butland
Eberechi Eze
James Tomkins
Jaïro Riedewald
Jesuran Rak Sakyi
Nathan Ferguson
Aston Villa
https://fbref.com/en/squads/8602292d/Aston-Villa-Stats
Matty Cash
Emiliano Martínez
Tyrone Mings
John McGinn
Ollie Watkins
Douglas Luiz
Ezri Konsa
Jacob Ramsey
Danny Ings
Emi Buendía
Matt Targett
Philippe Coutinho
Lucas Digne
Ashley Young
Marvelous Nakamba
Calum Chambers
Leon Bailey
Axel Tuanzebe
Kortney Hause
Anwar El Ghazi
Morgan Sanson
Carney Chukwuemeka
Bertrand Traoré
Tim Iroegbunam
Jed Steer
Cameron Archer
Keinan Davis
Trézéguet
Jaden Philogene Bidace
Wesley Moraes
Southampton
https://fbref.com/en/squads/33c895d4/Southampton-Stats
James Ward-Prowse
Oriol Romeu
Mohammed Salisu
Jan Bednarek
Kyle Walker-Peters
Valentino Livramento
Che Adams
Mohamed Elyounoussi
Armando Broja
Nathan Redmond
Fraser Forster
Romain Perraud
Alex McCarthy
Adam Armstrong
Stuart Armstrong
Ibrahima Diallo
Nathan Tella
Lyanco
Jack Stephens
Moussa Djenepo
Theo Walcott
Yan Valery
Shane Long
Willy Caballero
William Smallbone
Everton
https://fbref.com/en/squads/d3fd31cc/Everton-Stats
Jordan Pickford
Michael Keane
Séamus Coleman
Richarlison
Abdoulaye Doucouré
Demarai Gray
Anthony Gordon
Allan
Ben Godfrey
Mason Holgate
Alex Iwobi
Andros Townsend
Dominic Calvert-Lewin
Lucas Digne
Vitaliy Mykolenko
Yerry Mina
Jonjoe Kenny
Salomón Rondón
Fabian Delph
André Gomes
Donny van de Beek
Jarrad Branthwaite
Asmir Begović
Tom Davies
Jean-Philippe Gbamin
Ellis Simms
Dele Alli
Lewis Dobbin
Tyler Onyango
Anwar El Ghazi
Cenk Tosun
Moise Kean
Burnley
https://fbref.com/en/squads/943e8050/Burnley-Stats
Nick Pope
Dwight McNeil
James Tarkowski
Josh Brownhill
Charlie Taylor
Ashley Westwood
Ben Mee
Matthew Lowton
Backing off 0.6 seconds afters 1 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/9a9c05db/matchlogs/2021-2022/summary/Matthew-Lowton-Match-Logs',) and kwargs {}
Backing off 0.9 seconds afters 2 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/9a9c05db/matchlogs/2021-2022/summary/Matthew-Lowton-Match-Logs',) and kwargs {}
Backing off 1.5 seconds afters 3 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/9a9c05db/matchlogs/2021-2022/summary/Matthew-Lowton-Match-Logs',) and kwargs {}
Backing off 3.7 seconds afters 4 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/9a9c05db/matchlogs/2021-2022/summary/Matthew-Lowton-Match-Logs',) and kwargs {}
Backing off 6.5 seconds afters 5 tries calling function <function get_table at 0x00000201A834C9D8> with args ('https://fbref.com/en/players/9a9c05db/matchlogs/2021-2022/summary/Matthew-Lowton-Match-Logs',) and kwargs {}
Maxwel Cornet
Jack Cork
Connor Roberts
Nathan Collins
Aaron Lennon
Wout Weghorst
Chris Wood
Jay Rodriguez
Jóhann Berg Guðmundsson
Erik Pieters
Ashley Barnes
Matěj Vydra
Kevin Long
Wayne Hennessey
Dale Stephens
Leeds United
https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats
Illan Meslier
Stuart Dallas
Raphael Dias Belloli
Jack Harrison
Daniel James
Diego Llorente
Luke Ayling
Rodrigo
Mateusz Klich
Pascal Struijk
Liam Cooper
Junior Firpo
Adam Forshaw
Kalvin Phillips
Robin Koch
Tyler Roberts
Jamie Shackleton
Patrick Bamford
Joe Gelhardt
Lewis Bate
Charlie Cresswell
Cody Drameh
Sam Greenwood
Leo Fuhr Hjelde
Crysencio Summerville
Kristoffer Klaesson
Hélder Costa
Liam McCarron
Stuart McKinstry
Watford
https://fbref.com/en/squads/2abfe087/Watford-Stats
Moussa Sissoko
Emmanuel Dennis
Craig Cathcart
Ben Foster
Joshua King
Kiko Femenía
Juraj Kucka
Ismaila Sarr
Tom Cleverley
Samir Santos
Hassane Kamara
Imran Louza
William Troost-Ekong
João Pedro
Adam Masina
Cucho
Christian Kabasele
Daniel Bachmann
Jeremy Ngakia
Edo Kayembe
Danny Rose
Ken Sema
Francisco Sierralta
Oghenekaro Etebo
Ozan Tufan
Samuel Kalu
Nicolas Nkoulou
Dan Gosling
Ashley Fletcher
Troy Deeney
Norwich City
https://fbref.com/en/squads/1c781004/Norwich-City-Stats
Teemu Pukki
Grant Hanley
Max Aarons
Kenny McLean
Tim Krul
Ben Gibson
Pierre Lees-Melou
Milot Rashica
Brandon Williams
Billy Gilmour
Mathias Normann
Josh Sargent
Dimitris Giannoulis
Ozan Kabak
Sam Byram
Kieran Dowell
Angus Gunn
Lukas Rupp
Adam Idah
Przemysław Płacheta
Jakob Sørensen
Todd Cantwell
Andrew Omobamidele
Christos Tzolis
Christoph Zimmermann
Tony Springett
Jon Rowe
Bali Mumba

In [79]:
# df_enhanced = df_enhanced_copy.copy()

In [80]:
# get the player name matching dictionary
with open(path/'match_list.json') as f:
  match_list = json.load(f)

match_list

{'Fabinho': 'Fabio Henrique Tavares',
 'Alisson': 'Alisson Ramses Becker',
 'Joël Matip': 'Joel Matip',
 'Joe Gomez': 'Joseph Gomez',
 'Naby Keïta': 'Naby Keita',
 'Adrián': 'Adrián San Miguel del Castillo',
 'Thiago Alcántara': 'Thiago Alcántara do Nascimento',
 'Allan': 'Allan Marques Loureiro',
 'Richarlison': 'Richarlison de Andrade',
 'Gylfi Sigurðsson': 'Gylfi Sigurdsson',
 'Séamus Coleman': 'Seamus Coleman',
 'André Gomes': 'André Filipe Tavares Gomes',
 'Bernard': 'Bernard Anício Caldeira Duarte',
 'Çağlar Söyüncü': 'Çaglar Söyüncü',
 'Bruno Fernandes': 'Bruno Miguel Borges Fernandes',
 'Fred': 'Frederico Rodrigues de Paula Santos',
 'Nemanja Matić': 'Nemanja Matic',
 'Alex Telles': 'Alex Nicolao Telles',
 'Pierre Højbjerg': 'Pierre-Emile Højbjerg',
 'Son Heung-min': 'Heung-Min Son',
 'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
 'Érik Lamela': 'Erik Lamela',
 'Dele Alli': 'Bamidele Alli',
 'Carlos Vinícius': 'Carlos Vinicius Alves Morais',
 'Ederson': 'Ederson Santana de Moraes',
 'Rodri': 'Rodrigo Hernandez',
 'Rúben Dias': 'Rúben Santos Gato Alves Dias',
 'João Cancelo': 'João Pedro Cavaco Cancelo',
 'İlkay Gündoğan': 'Ilkay Gündogan',
 'Gabriel Jesus': 'Gabriel Fernando de Jesus',
 'Ferrán Torres': 'Ferran Torres',
 'Bernardo Silva': 'Bernardo Mota Veiga de Carvalho e Silva',
 'Fernandinho': 'Fernando Luiz Rosa',
 'Eric García': 'Eric Garcia',
 'Matty Cash': 'Matthew Cash',
 'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
 'Ezri Konsa': 'Ezri Konsa Ngoyo',
 'Trézéguet': 'Mahmoud Ahmed Ibrahim Hassan',
 'Ben Chilwell': 'Benjamin Chilwell',
 'Thiago Silva': 'Thiago Emiliano da Silva',
 'Mateo Kovačić': 'Mateo Kovacic',
 'Jorginho': 'Jorge Luiz Frello Filho',
 'Emerson Palmieri': 'Emerson Palmieri dos Santos',
 'Oriol Romeu': 'Oriol Romeu Vidal',
 'Dan Nlundulu': "Daniel N'Lundulu",
 'Łukasz Fabiański': 'Lukasz Fabianski',
 'Tomáš Souček': 'Tomas Soucek',
 'Vladimír Coufal': 'Vladimir Coufal',
 'Felipe Anderson': 'Felipe Anderson Pereira Gomes',
 'Rui Patrício': 'Rui Pedro dos Santos Patrício',
 'Pedro Neto': 'Pedro Lomba Neto',
 'Daniel Podence': 'Daniel Castelo Podence',
 'Nélson Semedo': 'Nélson Cabral Semedo',
 'Rúben Neves': 'Rúben Diogo da Silva Neves',
 'João Moutinho': 'João Filipe Iria Santos Moutinho',
 'Rayan Aït Nouri': 'Rayan Ait Nouri',
 'Fábio Silva': 'Fabio Silva',
 'Rúben Vinagre': 'Rúben Gonçalo Silva Nascimento Vinagre',
 'Vitinha': 'Vitor Ferreira',
 'Rodrigo': 'Rodrigo Moreno',
 'Pablo Hernández': 'Pablo Hernández Domínguez',
 'Ian Carlo Poveda': 'Ian Carlo Poveda-Ocampo',
 'Joelinton': 'Joelinton Cássio Apolinário de Lira',
 'Luka Milivojević': 'Luka Milivojevic',
 'Jaïro Riedewald': 'Jairo Riedewald',
 'Gabriel Dos Santos': 'Gabriel Magalhães',
 'Willian': 'Willian Borges Da Silva',
 'Dani Ceballos': 'Daniel Ceballos Fernández',
 'David Luiz': 'David Luiz Moreira Marinho',
 'Eddie Nketiah': 'Edward Nketiah',
 'Joe Willock': 'Joseph Willock',
 'Sead Kolašinac': 'Sead Kolasinac',
 'Martinelli': 'Gabriel Teodoro Martinelli Silva',
 'Solly March': 'Solomon March',
 'Bernardo': 'Bernardo Fernandes da Silva Junior',
 'Jóhann Berg Guðmundsson': 'Johann Berg Gudmundsson',
 'Matěj Vydra': 'Matej Vydra',
 'Andre-Frank Zambo Anguissa': 'André-Frank Zambo Anguissa',
 'Semi Ajayi': 'Oluwasemilogo Adesewo Ibidapo Ajayi',
 'Branislav Ivanović': 'Branislav Ivanovic',
 'Filip Krovinović': 'Filip Krovinovic',
 'Ahmed Hegazi': 'Ahmed El-Sayed Hegazi',
 'Harvey Elliot': 'Harvey Elliott',
 'Angeliño': 'Angelo Ogbonna',
 'Thomas Doyle': 'Tommy Doyle',
 'Diogo Dalot': 'José Diogo Dalot Teixeira',
 'Pedro': 'Pedro Rodríguez Ledesma',
 'Ricardo Pereira': 'Ricardo Domingos Barbosa Pereira',
 'Gedson Fernandes': 'Gedson Carvalho Fernandes',
 "Georges-Kévin N'Koudou": 'Georges-Kévin Nkoudou',
 'Jonny Castro': 'Jonathan Castro Otto',
 'Jesús Vallejo': 'Jesús Vallejo Lázaro',
 'Bruno Jordão': 'Bruno André Cavaco Jordao',
 'Mattéo Guendouzi': 'Matteo Guendouzi',
 'Richairo Živković': 'Richairo Zivkovic',
 'Danny Drinkwater': 'Daniel Drinkwater',
 'Martin Dúbravka': 'Martin Dubravka',
 'Yoshinori Mutō': 'Yoshinori Muto',
 'Ki Sung-yueng': 'Sung-yueng Ki',
 'Roberto': 'Roberto Jimenez Gago',
 'Javier Hernández': 'Javier Hernández Balcázar',
 'Frederic Guilbert': 'Frédéric Guilbert',
 'Björn Engels': 'Bjorn Engels',
 'Pepe Reina': 'José Reina',
 'Jota': 'José Ignacio Peleteiro Romallo',
 'Arnaut Groeneveld': 'Arnaut Danjuma Groeneveld',
 'Étienne Capoue': 'Etienne Capoue',
 'Kiko Femenía': 'Francisco Femenía Far',
 'Ismaila Sarr': 'Ismaila Sarr',
 'João Pedro': 'João Pedro Junqueira de Jesus',
 'Max Aarons': 'Max Aarons',
 'Emi Buendía': 'Emiliano Buendía Stati',
 'Mario Vrančić': 'Mario Vrancic',
 'Josip Drmić': 'Josip Drmic',
 'Ralf Fährmann': 'Ralf Fahrmann',
 'Danilo': 'Danilo Luiz da Silva',
 'Petr Čech': 'Petr Cech',
 'Idrissa Gana Gueye': 'Idrissa Gueye',
 'Marko Arnautović': 'Marko Arnautovic',
 'Xande Silva': 'Alexandre Nascimento Costa Silva',
 'Julián Speroni': 'Julian Speroni',
 'Kenedy': 'Robert Kenedy Nunes do Nascimento',
 'Joselu': 'Jose Luis Mato Sanmartín',
 'Asmir Begović': 'Asmir Begović',
 'Kayne Ramsey': 'Kayne Ramsay',
 'Bruno': 'Bruno Saltor Grau',
 'Junior Hoilett': 'David Junior Hoilett',
 'Greg Cunningham': 'Greg Cunninghamm',
 'Jazz Richards': 'Ashley Darel Jazz Richards',
 'Jean Seri': 'Jean Michael Seri',
 'Fabricio': 'Fabricio Agosto Ramírez',
 'Lazar Marković': 'Lazar Markovic',
 'Mathias Jørgensen': 'Mathias Jorgensen',
 'Steve Mounié': 'Steve Mounie',
 'Jon Gorenc Stanković': 'Jon Gorenc Stankovic',
 'Matty Daly': 'Matthew Daly',
 'Yaya Touré': 'Gnegneri Yaya Touré',
 'Brahim Díaz': 'Brahim Diaz',
 'Zlatan Ibrahimović': 'Zlatan Ibrahimovic',
 'Marko Grujić': 'Marko Grujic',
 'Charly Musonda Jr.': 'Charly Musonda',
 'Nikola Vlašić': 'Nikola Vlasic',
 'Aleksandar Dragović': 'Aleksandar Dragovic',
 'Eldin Jakupović': 'Eldin Jakupovic',
 'Rob Elliot': 'Robert Elliot',
 'Jesús Gámez': 'Jesús Gámez Duarte',
 'Massadio Haïdara': 'Massadio Haidara',
 'Lee Chung-yong': 'Chung-yong Lee',
 'Freddie Ladapo': 'Olayinka Fredrick Oladotun Ladapo',
 'João Mário': 'João Mário Naval Costa Eduardo',
 'José Fonte': 'Jose Fonte',
 'Younès Kaboul': 'Younes Kaboul',
 'Izzy Brown': 'Isaiah Brown',
 'Dušan Tadić': 'Dusan Tadic',
 'Àngel Rangel': 'Angel Rangel',
 'Badou Ndiaye': 'Papa Alioune Ndiaye',
 'Jesé': 'Jesé Rodríguez Ruiz',
 'Tom Edwards': 'Thomas Edwards',
 'Kostas Stafylidis': 'Konstantinos Stafylidis',
 'Lasse Sørensen': 'Lasse Sorenson',
 'Bojan Krkić': 'Bojan Krkic',
 'Allan Nyom': 'Allan-Roméo Nyom',
 'Ahmed Elmohamady': 'Ahmed El Mohamady',
 'Hélder Costa': 'Hélder Wander Sousa de Azevedo e Costa',
 'Mohamed Elneny': 'Mohamed Naser El Sayed Elneny',
 'Emile Smith-Rowe': 'Emile Smith Rowe',
 'Ivan Cavaleiro': 'Ivan Ricardo Neves Abreu Cavaleiro',
 'Bobby Reid': 'Bobby Decordova-Reid',
 'Ahmed El-Sayed Hegazi': 'Ahmed El-Sayed Hegazy',
 'Kiko Casilla': 'Francisco Casilla Cortés',
 'Willian José': 'Willian José Da Silva',
 'Kostas Tsimikas': 'Konstantinos Tsimikas',
 'Okay Yokuşlu': 'Okay Yokuslu',
 'Khanya Leshabela': 'Thakgalo Leshabela',
 'Jaden Philogene Bidace': 'Jaden Philogene-Bidace',
 'William Thomas Fish': 'William Fish',
 'David Raya': 'David Raya Martin',
 'Oghenekaro Etebo': 'Oghenekaro Peter Etebo',
 'Ismaïla Sarr': 'Ismaila Sarr',
 'Cucho': 'Juan Camilo Hernández Suárez',
 'Enoch Mwepu': 'Enock Mwepu',
 'Emiliano Buendía': 'Emiliano Buendía StatiJosé Malheiro de Sá',
 'José Sá': 'José Malheiro de Sá',
 'Francisco Trincão': 'Francisco Machado Mota de Castro Trincão',
 'Valentino Livramento': 'Tino Livramento',
 'Nuno Tavares': 'Nuno Varela Tavares',
 'Jesuran Rak Sakyi': 'Jesurun Rak-Sakyi',
 'Maximillian Aarons': 'Max Aarons',
 'Josh Sargent': 'Joshua Sargent',
 'Junior Firpo': 'Héctor Junior Firpo Adames',
 'Imran Louza': 'Imrân Louza',
 'Bryan': 'Bryan Gil Salvatierra',
 'Kiernan Dewsbury Hall': 'Kiernan Dewsbury-Hall',
 'Cristiano Ronaldo': 'Cristiano Ronaldo dos Santos Aveiro',
 'Emerson': 'Emerson Aparecido Leite de Souza Junior',
 'Mads Roerslev': 'Mads Roerslev Rasmussen',
 'Odsonne Édouard': 'Odsonne Edouard',
 'Hwang Hee-chan': 'Hee-Chan Hwang',
 'Asmir Begovic': 'Asmir Begović',
 'Caoimhín Kelleher': 'Caoimhin Kelleher',
 'Lyanco': 'Lyanco Evangelista Silveira Neves Vojnovic',
 'Przemysław Płacheta': 'Przemyslaw Placheta',
 'James Mcatee': 'James McAtee',
 'Jakob Sørensen': 'Jacob Sørensen',
 'Alex Král': 'Alex Kral',
 'Jon Rowe': 'Jonathan Rowe',
 'Toti Gomes': 'Toti António Gomes',
 'Philippe Coutinho': 'Philippe Coutinho Correia',
 'Vitaliy Mykolenko': 'Vitalii Mykolenko',
 'Samir Santos': 'Samir Caetano de Souza Santos',
 'Chiquinho': 'Francisco Jorge Tomás Oliveira',
 'Josh Dasilva': 'Pelenda Joshua Dasilva',
 'Bruno Guimarães': 'Bruno Guimarães Rodriguez Moura',
 'Kayky Chagas': 'Kayky da Silva Chagas',
 'Tariqe Fosu': 'Tariqe Fosu-Henry',
 'Alejandro Garnacho': 'Alejandro Garnacho Ferreyra',
 'CJ Egan-Riley': 'Conrad Egan-Riley'}

In [81]:
team_list = {}
team_list['Brighton'] = 'Brighton and Hove Albion'
team_list['Leeds United'] = 'Leeds'
team_list['Manchester Utd'] = 'Manchester United'
team_list['Newcastle Utd'] = 'Newcastle United'
team_list['Norwich City'] = 'Norwich'
team_list['Sheffield Utd'] = 'Sheffield United'
team_list['Tottenham'] = 'Tottenham Hotspur'
team_list['West Brom'] = 'West Bromwich Albion'
team_list['West Ham'] = 'West Ham United'
team_list['Wolves'] = 'Wolverhampton Wanderers'

In [82]:
df_enhanced = df_enhanced.loc[df_enhanced[df_enhanced['round'].str[-2:] != 'on'].index]
df_enhanced = df_enhanced.loc[df_enhanced[df_enhanced['squad'] != 'CSKA Moscow'].index]

In [83]:
# replace non-matching names/teams and extract gw as integer
df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)
df_enhanced['squad'] = df_enhanced['squad'].replace(team_list)
df_enhanced['round'] = df_enhanced['round'].str[-2:].astype('int')

In [84]:
# remove duplicated (happens when players transferred within season)
df_enhanced = df_enhanced.drop_duplicates()

In [85]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10451,2021-2022,Jon Rowe,2022-04-23,Norwich,Premier League,34,1,1,19,11,...,0.1,1,0,11,13,84.6,14,1,1,Jonathan Rowe
10452,2021-2022,Jon Rowe,2022-04-30,Norwich,Premier League,35,0,0,9,4,...,0.0,0,0,3,4,75.0,7,0,3,Jonathan Rowe
10453,2021-2022,Jon Rowe,2022-05-11,Norwich,Premier League,21,0,0,7,14,...,0.0,0,0,2,3,66.7,4,0,0,Jonathan Rowe
10454,2021-2022,Jon Rowe,2022-05-15,Norwich,Premier League,37,0,0,5,0,...,0.1,1,0,3,5,60.0,5,1,1,Jonathan Rowe
10455,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [86]:
# create date field in same format as enhanced data
df_latest['date'] = df_latest['kickoff_time'].str[:10]

In [87]:
# check if any names aren't matching
enhanced_players = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['alt_name'].unique().tolist()
standard_players = df_latest['player'].unique().tolist()

unmatched_players = [x for x in enhanced_players if x not in standard_players]
unmatched_players

[]

In [88]:
# check if any teams aren't matching
enhanced_teams = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['squad'].unique().tolist()
standard_teams = df_latest['team'].unique().tolist()

unmatched_teams = [x for x in enhanced_teams if x not in standard_teams]
unmatched_teams

[]

In [89]:
# any additional corrections
# match_list['CJ Egan-Riley'] = 'Conrad Egan-Riley'
# match_list['Josh Dasilva'] = 'Pelenda Joshua Dasilva'
# match_list['Bruno Guimarães'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Samir Santos'] = 'Samir Caetano de Souza Santos'
# match_list['Hwang Hee-chan'] = 'Hee-Chan Hwang'

# match_list['Sadio Man�'] = 'Sadio Mané'
# match_list['Jo�l Matip'] = 'Joel Matip'
# match_list['Thiago Alc�ntara'] = 'Thiago Alcántara do Nascimento'
# match_list['Naby Ke�ta'] = 'Naby Keita'
# match_list['Luis D�az'] = 'Luis Díaz'
# match_list['Jos� S�'] = 'José Malheiro de Sá'
# match_list['Romain Sa�ss'] = 'Romain Saïss'
# match_list['N�lson Semedo'] = 'Nélson Cabral Semedo'
# match_list['Ra�l Jim�nez'] = 'Raúl Jiménez'
# match_list['Jo�o Moutinho'] = 'João Filipe Iria Santos Moutinho'
# match_list['R�ben Neves'] = 'Rúben Diogo da Silva Neves'
# match_list['Rayan A�t Nouri'] = 'Rayan Ait Nouri'
# match_list['Fernando Mar�al'] = 'Fernando Marçal'
# match_list['Emiliano Mart�nez'] = 'Emiliano Martínez'
# match_list['Emi Buend�a'] = 'Emiliano Buendía Stati'
# match_list['Fabian Sch�r'] = 'Fabian Schär'
# match_list['Martin D�bravka'] = 'Martin Dubravka'
# match_list['Miguel Almir�n'] = 'Miguel Almirón'
# match_list['Bruno Guimar�es'] = 'Bruno Guimarães Rodriguez Moura'
# match_list['Kiko Femen�a'] = 'Francisco Femenía Far'

In [90]:
# replace additional non-matching names
# df_enhanced['alt_name'] = df_enhanced['player'].replace(match_list)

In [91]:
# make sure there are no non matches after update
# enhanced_teams = df_enhanced[df_enhanced['date'].isin(df_latest['date'].unique())]['squad'].unique().tolist()
# standard_teams = df_latest['team'].unique().tolist()

# unmatched_teams = [x for x in enhanced_teams if x not in standard_teams]
# unmatched_teams

In [92]:
# if match list was updated then update the file
# json_file = json.dumps(match_list)
# f = open(path/"match_list.json","w")
# f.write(json_file)
# f.close()

In [93]:
# check there are no duplicates in the join fields for the enhanced data
assert(len(df_enhanced[df_enhanced.duplicated(subset=['alt_name', 'date'], keep=False)]) == 0)

In [94]:
df_latest[df_latest.duplicated(subset=['date','player','team'], keep=False)]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date]
Index: []

[0 rows x 36 columns]

In [95]:
# check there are no duplicates in the join fields for the standard data
assert(len(df_train[df_train.duplicated(subset=['date','player','team'])]) == 0)

In [96]:
# df_train[df_train.duplicated(subset=['date','player','team'])]

In [97]:
# join standard and enhanced dataframes
df_latest_further = df_latest.merge(df_enhanced.drop(['player', 'season', 'round'], axis=1), 
                                   left_on=['date', 'player', 'team'], 
                                   right_on=['date', 'alt_name', 'squad'], how='left')

In [98]:
# drop the alt name field and check the length of the standard
# dataframe has not increased
df_latest_further = df_latest_further.drop(['alt_name'], axis=1)
assert(len(df_latest_further) == len(df_latest_further))

In [99]:
# add crowds field
df_latest_further['crowds'] = 1

In [100]:
assert(sum(df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()) == 0)

In [101]:
df_latest_further[df_latest_further['minutes'] > 0][df_latest_further[df_latest_further['minutes'] > 0]['xg'].isnull()]

Empty DataFrame
Columns: [player, gw, position, minutes, team, opponent_team, relative_market_value_team, relative_market_value_opponent_team, was_home, total_points, assists, bonus, bps, clean_sheets, creativity, goals_conceded, goals_scored, ict_index, influence, own_goals, penalties_missed, penalties_saved, red_cards, saves, selected, team_a_score, team_h_score, threat, transfers_balance, transfers_in, transfers_out, yellow_cards, kickoff_time, season, play_proba, date, squad, comp, shots_total, shots_on_target, touches, pressures, tackles, interceptions, blocks, xg, npxg, xa, sca, gca, passes_completed, passes, passes_pct, carries, dribbles_completed, dribbles, crowds]
Index: []

[0 rows x 57 columns]

In [102]:
df_enhanced

,season,player,date,squad,comp,round,shots_total,shots_on_target,touches,pressures,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,alt_name
0,2021-2022,Ederson,2021-08-15,Manchester City,Premier League,1,0,0,22,0,...,0.0,2,0,20,22,90.9,10,0,0,Ederson Santana de Moraes
1,2021-2022,Ederson,2021-08-21,Manchester City,Premier League,2,0,0,14,0,...,0.0,0,0,12,12,100.0,6,0,0,Ederson Santana de Moraes
2,2021-2022,Ederson,2021-08-28,Manchester City,Premier League,3,0,0,37,0,...,0.0,0,0,31,37,83.8,25,0,0,Ederson Santana de Moraes
3,2021-2022,Ederson,2021-09-11,Manchester City,Premier League,4,0,0,26,0,...,0.0,0,0,22,24,91.7,10,0,0,Ederson Santana de Moraes
4,2021-2022,Ederson,2021-09-18,Manchester City,Premier League,5,0,0,40,0,...,0.0,0,0,39,39,100.0,28,0,0,Ederson Santana de Moraes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10451,2021-2022,Jon Rowe,2022-04-23,Norwich,Premier League,34,1,1,19,11,...,0.1,1,0,11,13,84.6,14,1,1,Jonathan Rowe
10452,2021-2022,Jon Rowe,2022-04-30,Norwich,Premier League,35,0,0,9,4,...,0.0,0,0,3,4,75.0,7,0,3,Jonathan Rowe
10453,2021-2022,Jon Rowe,2022-05-11,Norwich,Premier League,21,0,0,7,14,...,0.0,0,0,2,3,66.7,4,0,0,Jonathan Rowe
10454,2021-2022,Jon Rowe,2022-05-15,Norwich,Premier League,37,0,0,5,0,...,0.1,1,0,3,5,60.0,5,1,1,Jonathan Rowe
10455,2021-2022,Bali Mumba,2021-08-21,Norwich,Premier League,2,0,0,19,12,...,0.0,0,0,7,10,70.0,9,0,1,Bali Mumba

In [103]:
df_train_new = pd.concat([df_train, df_latest_further], ignore_index=True, axis=0, sort=False)

In [104]:
df_train_new[df_train_new['player'] == 'Harry Kane'].tail()

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
136179,Harry Kane,34,4,90,Tottenham Hotspur,Brentford,NaN,NaN,False,2,...,0.0,1.0,0.0,10.0,15.0,66.7,17.0,0.0,2.0,1
136948,Harry Kane,35,4,90,Tottenham Hotspur,Leicester City,NaN,NaN,True,6,...,0.0,1.0,0.0,17.0,29.0,58.6,25.0,1.0,4.0,1
138421,Harry Kane,36,4,90,Tottenham Hotspur,Liverpool,NaN,NaN,False,2,...,0.1,5.0,1.0,9.0,20.0,45.0,19.0,3.0,3.0,1
138422,Harry Kane,36,4,90,Tottenham Hotspur,Arsenal,NaN,NaN,True,13,...,0.2,4.0,0.0,15.0,19.0,78.9,20.0,2.0,2.0,1
138924,Harry Kane,37,4,90,Tottenham Hotspur,Burnley,NaN,NaN,True,7,...,0.0,3,0,11,27,40.7,37,1,3,1

In [105]:
df_train_new.tail(10)

,player,gw,position,minutes,team,opponent_team,relative_market_value_team,relative_market_value_opponent_team,was_home,total_points,...,xa,sca,gca,passes_completed,passes,passes_pct,carries,dribbles_completed,dribbles,crowds
139501,Yoane Wissa,37,3,75,Brentford,Everton,NaN,NaN,False,11,...,0.0,0,0,13,19,68.4,22,1,1,1
139502,Youri Tielemans,37,3,90,Leicester City,Watford,NaN,NaN,False,4,...,0.7,3,1,46,57,80.7,37,0,0,1
139503,Youri Tielemans,37,3,0,Leicester City,Chelsea,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139504,Yves Bissouma,37,3,90,Brighton and Hove Albion,Leeds,NaN,NaN,False,8,...,0.2,2,1,32,33,97.0,28,1,2,1
139505,Zach Awe,37,2,0,Arsenal,Newcastle United,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139506,Zack Steffen,37,1,0,Manchester City,West Ham United,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139507,Zak Swanson,37,2,0,Arsenal,Newcastle United,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139508,Álvaro Fernández,37,1,0,Brentford,Everton,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139509,Çaglar Söyüncü,37,2,0,Leicester City,Watford,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
139510,Çaglar Söyüncü,37,2,0,Leicester City,Chelsea,NaN,NaN,False,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [106]:
df_latest_further.shape

(882, 57)

In [107]:
df_train_new.shape

(139511, 59)

In [108]:
# save latest training set to csv
# overwrite existing one
df_train_new.to_csv(path/'train_v8.csv')

In [7]:
last_gw = 0

In [8]:
# get fixtures
fixtures = pd.read_csv(path/'2022-23/fixtures.csv')
team_dict = teams[['team_2223', 'team']].dropna().set_index('team_2223').to_dict()['team']

fixtures['home_team'] = fixtures['team_h'].replace(team_dict)
fixtures['away_team'] = fixtures['team_a'].replace(team_dict)
fixtures = fixtures[['home_team', 'away_team', 'kickoff_time', 'event']]
fixtures = fixtures.rename(columns={'event':'gw'})


# use these two lines if updating play_proba later in week
# current_gw = last_gw
# df_train_new = pd.read_csv(path/'train_v7.csv', index_col=0, dtype={'season':str,
#                                                                     'comp':str,
#                                                                     'squad':str})

# set starting gameweek (where are we right now in the season)
current_gw = last_gw + 1
fixtures = fixtures[fixtures['gw'] >= current_gw].sort_values(by=['gw'])
fixtures['match_no'] = np.arange(fixtures.shape[0])

In [9]:
fixtures.head(50)

,home_team,away_team,kickoff_time,gw,match_no
0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,1,0
1,Fulham,Liverpool,2022-08-06T11:30:00Z,1,1
2,Bournemouth,Aston Villa,2022-08-06T14:00:00Z,1,2
3,Leeds,Wolverhampton Wanderers,2022-08-06T14:00:00Z,1,3
4,Newcastle United,Nottingham Forest,2022-08-06T14:00:00Z,1,4
5,Tottenham Hotspur,Southampton,2022-08-06T14:00:00Z,1,5
6,Everton,Chelsea,2022-08-06T16:30:00Z,1,6
7,Leicester City,Brentford,2022-08-07T13:00:00Z,1,7
8,Manchester United,Brighton and Hove Albion,2022-08-07T13:00:00Z,1,8
9,West Ham United,Manchester City,2022-08-07T15:30:00Z,1,9
19,Liverpool,Crystal Palace,2022-08-15T19:00:00Z,2,10
18,Chelsea,Tottenham Hotspur,2022-08-14T15:30:00Z,2,11
17,Nottingham Forest,West Ham United,2022-08-14T13:00:00Z,2,12
16,Brentford,Manchester United,2022-08-13T16:30:00Z,2,13
15,Wolverhampton Wanderers,Fulham,2022-08-13T14:00:00Z,2,14
12,Brighton and Hove Albion,Newcastle United,2022-08-13T14:00:00Z,2,15
13,Manchester City,Bournemouth,2022-08-13T14:00:00Z,2,16
11,Arsenal,Leicester City,2022-08-13T14:00:00Z,2,17
10,Aston Villa,Everton,2022-08-13T11:30:00Z,2,18
14,Southampton,Leeds,2022-08-13T14:00:00Z,2,19
26,Leeds,Chelsea,2022-08-21T13:00:00Z,3,20
29,Manchester United,Liverpool,2022-08-22T19:00:00Z,3,21
28,Newcastle United,Manchester City,2022-08-21T15:30:00Z,3,22
27,West Ham United,Brighton and Hove Albion,2022-08-21T13:00:00Z,3,23
25,Bournemouth,Arsenal,2022-08-20T16:30:00Z,3,24
21,Crystal Palace,Aston Villa,2022-08-20T14:00:00Z,3,25
23,Fulham,Brentford,2022-08-20T14:00:00Z,3,26
22,Everton,Nottingham Forest,2022-08-20T14:00:00Z,3,27
20,Tottenham Hotspur,Wolverhampton Wanderers,2022-08-20T11:30:00Z,3,28
24,Leicester City,Southampton,2022-08-20T14:00:00Z,3,29
39,Nottingham Forest,Tottenham Hotspur,2022-08-28T15:30:00Z,4,30
38,Wolverhampton Wanderers,Newcastle United,2022-08-28T13:00:00Z,4,31
37,Aston Villa,West Ham United,2022-08-28T13:00:00Z,4,32
36,Arsenal,Fulham,2022-08-27T16:30:00Z,4,33
35,Manchester City,Crystal Palace,2022-08-27T14:00:00Z,4,34
34,Liverpool,Bournemouth,2022-08-27T14:00:00Z,4,35
32,Brighton and Hove Albion,Leeds,2022-08-27T14:00:00Z,4,36
31,Brentford,Everton,2022-08-27T14:00:00Z,4,37
30,Southampton,Manchester United,2022-08-27T11:30:00Z,4,38
33,Chelsea,Leicester City,2022-08-27T14:00:00Z,4,39
46,Manchester City,Nottingham Forest,2022-08-31T18:30:00Z,5,40
49,Leicester City,Manchester United,2022-09-01T19:00:00Z,5,41
48,Liverpool,Newcastle United,2022-08-31T19:00:00Z,5,42
45,Bournemouth,Wolverhampton Wanderers,2022-08-31T18:30:00Z,5,43
47,West Ham United,Tottenham Hotspur,2022-08-31T18:45:00Z,5,44
43,Leeds,Everton,2022-08-30T19:00:00Z,5,45
42,Southampton,Chelsea,2022-08-30T18:45:00Z,5,46
44,Arsenal,Aston Villa,2022-08-31T18:30:00Z,5,47
41,Fulham,Brighton and Hove Albion,2022-08-30T18:30:00Z,5,48
40,Crystal Palace,Brentford,2022-08-30T18:30:00Z,5,49

In [10]:
# add universal team codes for home and away teams
fixtures = fixtures.merge(teams, left_on='home_team', right_on='team', how='left')
fixtures = fixtures.merge(teams, left_on='away_team', right_on='team', how='left')
fixtures = fixtures[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 'team_code_x', 'team_code_y']]
fixtures.rename(index=str,
                columns={'team_code_x':'home_team_code',
                         'team_code_y':'away_team_code'},
                inplace=True)

In [11]:
fixtures.head()

,gw,match_no,home_team,away_team,kickoff_time,home_team_code,away_team_code
0,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,31,3
1,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,54,14
2,1,2,Bournemouth,Aston Villa,2022-08-06T14:00:00Z,91,7
3,1,3,Leeds,Wolverhampton Wanderers,2022-08-06T14:00:00Z,2,39
4,1,4,Newcastle United,Nottingham Forest,2022-08-06T14:00:00Z,4,17

In [12]:
# all_players.replace(to_replace='None', value=1, inplace=True)

In [14]:
all_players[all_players['play_proba_2223'] == '0']

,full_name,play_proba_2223,position_2223,id_2223,cost_2223,team_2223,web_name_2223
16,Nuno Varela Tavares,0,2,17,45,3,Tavares
55,Jaden Philogene-Bidace,0,3,55,45,7,Philogene-Bidace
79,Joe Rothwell,0,3,505,50,91,Rothwell
85,Sergi Canós Tenés,0,2,82,50,94,Canós
87,Kristoffer Ajer,0,2,84,45,94,Ajer
95,Ethan Pinnock,0,2,92,45,94,Pinnock
100,Marcus Forss,0,4,97,45,94,Forss
101,Dominic Thompson,0,2,98,40,94,Thompson
102,Mads Bidstrup,0,3,99,45,94,Bidstrup
103,Ellery Balcombe,0,1,100,40,94,Balcombe
124,Jakub Moder,0,3,117,45,36,Moder
128,Taylor Richards,0,3,121,45,36,Richards
129,Haydon Roberts,0,2,122,40,36,Roberts
185,Remi Matthews,0,1,495,40,31,Matthews
190,Salomón Rondón,0,4,177,50,11,Rondón
192,Andros Townsend,0,3,179,55,11,Townsend
209,Jarrad Branthwaite,0,2,196,40,11,Branthwaite
241,Ryan Bertrand,0,2,250,40,13,Bertrand
266,Luke Ayling,0,2,222,45,2,Ayling
270,Stuart Dallas,0,2,226,50,2,Dallas
273,Tyler Roberts,0,3,229,50,2,Roberts
275,Daniel James,0,3,231,60,2,James
276,Raphael Dias Belloli,0,3,232,70,2,Raphinha
278,Jamie Shackleton,0,3,234,45,2,Shackleton
283,Junior Firpo Adames,0,2,239,45,2,Firpo
298,Alex Oxlade-Chamberlain,0,3,278,50,14,Chamberlain
309,Caoimhin Kelleher,0,1,289,40,14,Kelleher
319,Rhys Williams,0,2,498,40,14,R.Williams
320,Ben Davies,0,2,499,40,14,Davies
333,Aymeric Laporte,0,2,309,60,43,Laporte
334,Zack Steffen,0,1,310,40,43,Steffen
377,Ciaran Clark,0,2,352,45,4,Clark
386,Dwight Gayle,0,4,361,45,4,Gayle
400,Jeff Hendrick,0,3,375,45,4,Hendrick
408,Brice Samba,0,1,382,45,17,Samba
415,Jonathan Panzo,0,2,389,40,17,Panzo
427,Omar Richards,0,2,511,45,17,Richards
446,Nathan Tella,0,3,412,50,20,Tella
449,Will Smallbone,0,3,415,45,20,Smallbone
453,Tino Livramento,0,2,419,45,20,Livramento
472,Steven Bergwijn,0,3,437,55,6,Bergwijn
477,Joe Rodon,0,2,442,40,6,Rodon
482,Dane Scarlett,0,4,447,45,6,Scarlett
488,Troy Parrott,0,4,453,45,6,Parrott
489,Richarlison de Andrade,0,4,454,85,6,Richarlison
509,Nayef Aguerd,0,2,472,50,21,Aguerd
515,Raúl Jiménez,0,4,476,70,39,Jiménez
527,Fabio Silva,0,4,488,55,39,Fabio Silva
529,Francisco Jorge Tomás Oliveira,0,3,490,50,39,Chiquinho

In [18]:
# join home team to all players for current season
home_df = fixtures.merge(all_players, 
               left_on='home_team_code', 
               right_on='team_2223', 
               how='left')

# pull out the required fields and rename columns
home_df = home_df[['gw', 'match_no', 'home_team', 'away_team', 'kickoff_time', 
                   'full_name', 'position_2223', 'cost_2223', 'play_proba_2223', 
                   'web_name_2223']]
home_df.rename(index=str, 
               columns={'home_team':'team',
                        'away_team':'opponent_team',
                        'full_name':'player',
                        'position_2223':'position',
                        'cost_2223':'price',
                        'play_proba_2223':'play_proba',
                        'web_name_2223':'short_name'},
              inplace=True)

# add home flag
home_df['was_home'] = True

In [15]:
# join away team to all players for current season
away_df = fixtures.merge(all_players, 
               left_on='away_team_code', 
               right_on='team_2223', 
               how='left')

# pull out the required fields and rename columns
away_df = away_df[['gw',  'match_no', 'away_team', 'home_team', 'kickoff_time', 
                   'full_name', 'position_2223', 'cost_2223', 'play_proba_2223', 
                   'web_name_2223']]
away_df.rename(index=str, 
               columns={'away_team':'team',
                        'home_team':'opponent_team',
                        'full_name':'player',
                        'position_2223':'position',
                        'cost_2223':'price',
                        'play_proba_2223':'play_proba',
                        'web_name_2223':'short_name'},
              inplace=True)

# add home flag
away_df['was_home'] = False

In [16]:
# look at away players
away_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,1,0,Arsenal,Crystal Palace,2022-08-05T19:00:00Z,Cédric Alves Soares,2,45,None,Cédric,False
1,1,0,Arsenal,Crystal Palace,2022-08-05T19:00:00Z,Bernd Leno,1,45,None,Leno,False
2,1,0,Arsenal,Crystal Palace,2022-08-05T19:00:00Z,Granit Xhaka,3,50,None,Xhaka,False
3,1,0,Arsenal,Crystal Palace,2022-08-05T19:00:00Z,Mohamed Elneny,3,45,None,Elneny,False
4,1,0,Arsenal,Crystal Palace,2022-08-05T19:00:00Z,Rob Holding,2,45,None,Holding,False

In [19]:
# look at home players
home_df.head()

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home
0,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Vicente Guaita,1,45,None,Guaita,True
1,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,James Tomkins,2,40,None,Tomkins,True
2,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,James McArthur,3,50,25,McArthur,True
3,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Christian Benteke,4,55,None,Benteke,True
4,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Joel Ward,2,45,None,Ward,True

In [119]:
# # calculate average minutes over last 5 gameweeks
# # first get last 5 gameweeks in current season
# recent_mins = df_train_new[(df_train_new['gw'] >= current_gw - 5) & 
#                            (df_train_new['season'] == season_names[0])][['player', 'minutes', 'play_proba']]

# # recent_mins = df_train_new[((df_train_new['gw'] >= 40 - 5) & 
# #                            (df_train_new['season'] == '1920')) | 
# #                            ((df_train_new['gw'] >= 1) & 
# #                            (df_train_new['season'] == '2021'))][['player', 'minutes', 'play_proba']]

# # exclude weeks where the player had an injury designation (i.e. keep where play_proba is 1)
# recent_mins = recent_mins[recent_mins['play_proba'] == 1]

# len(recent_mins)

# # average for each player
# recent_mins = recent_mins.groupby(['player'])['minutes'].mean().to_dict()

# recent_mins

In [20]:
# concatenate home and away players
remaining_season_df = home_df.append(away_df).reset_index(drop=True)

# add home and away team market values
remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2223'],
                                                left_on='team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df = remaining_season_df.merge(teams_mv[teams_mv['season'] == '2223'],
                                                left_on='opponent_team', 
                                                right_on='name', 
                                                how='left').drop(['name', 'season'], axis=1)

remaining_season_df.rename(index=str, 
                           columns={'relative_market_value_x':'relative_market_value_team',
                                    'relative_market_value_y':'relative_market_value_opponent_team'},
                           inplace=True)

# add season name
remaining_season_df['season'] = season_names[0]

# divide cost by 10 for actual cost
remaining_season_df['price'] = remaining_season_df['price']/10

# set availability probability
# 0 = 0% chance, 25 = 25% chance, etc
# 'None' or '100' = 100% chance
remaining_season_df.loc[remaining_season_df['play_proba'] == 'None', 'play_proba'] = 100
remaining_season_df['play_proba'] = remaining_season_df['play_proba'].astype('float') / 100

# cast position to integer
remaining_season_df['position'] = remaining_season_df['position'].astype(int)

# # add minutes based on last five fixtures
# remaining_season_df['minutes'] = remaining_season_df['player'].map(recent_mins)
# remaining_season_df['minutes'].fillna(0, inplace=True)

# # multiply minutes by play probability
# remaining_season_df['minutes'] = remaining_season_df['minutes'] * remaining_season_df['play_proba']

In [21]:
remaining_season_df.head(50)

,gw,match_no,team,opponent_team,kickoff_time,player,position,price,play_proba,short_name,was_home,relative_market_value_team,relative_market_value_opponent_team,season
0,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Vicente Guaita,1,4.5,1.00,Guaita,True,NaN,NaN,2223
1,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,James Tomkins,2,4.0,1.00,Tomkins,True,NaN,NaN,2223
2,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,James McArthur,3,5.0,0.25,McArthur,True,NaN,NaN,2223
3,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Christian Benteke,4,5.5,1.00,Benteke,True,NaN,NaN,2223
4,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Joel Ward,2,4.5,1.00,Ward,True,NaN,NaN,2223
5,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Nathaniel Clyne,2,4.5,1.00,Clyne,True,NaN,NaN,2223
6,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Luka Milivojevic,3,4.5,1.00,Milivojevic,True,NaN,NaN,2223
7,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jordan Ayew,3,5.5,1.00,Ayew,True,NaN,NaN,2223
8,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Wilfried Zaha,3,7.0,1.00,Zaha,True,NaN,NaN,2223
9,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jeffrey Schlupp,3,5.0,1.00,Schlupp,True,NaN,NaN,2223
10,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jack Butland,1,4.5,0.25,Butland,True,NaN,NaN,2223
11,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Will Hughes,3,5.0,1.00,Hughes,True,NaN,NaN,2223
12,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jairo Riedewald,3,4.5,1.00,Riedewald,True,NaN,NaN,2223
13,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Joachim Andersen,2,4.5,1.00,Andersen,True,NaN,NaN,2223
14,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Odsonne Edouard,4,5.5,1.00,Edouard,True,NaN,NaN,2223
15,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Marc Guéhi,2,4.5,1.00,Guéhi,True,NaN,NaN,2223
16,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jean-Philippe Mateta,4,5.5,1.00,Mateta,True,NaN,NaN,2223
17,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Eberechi Eze,3,5.5,1.00,Eze,True,NaN,NaN,2223
18,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Tyrick Mitchell,2,4.5,1.00,Mitchell,True,NaN,NaN,2223
19,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Michael Olise,3,5.5,0.50,Olise,True,NaN,NaN,2223
20,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Jesurun Rak-Sakyi,3,4.5,1.00,Rak-Sakyi,True,NaN,NaN,2223
21,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Malcolm Ebiowei,3,4.5,1.00,Ebiowei,True,NaN,NaN,2223
22,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Nathan Ferguson,2,4.0,1.00,Ferguson,True,NaN,NaN,2223
23,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Sam Johnstone,1,4.5,0.50,Johnstone,True,NaN,NaN,2223
24,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Remi Matthews,1,4.0,0.00,Matthews,True,NaN,NaN,2223
25,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Luke Plange,4,4.5,1.00,Plange,True,NaN,NaN,2223
26,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Cheick Doucouré,3,5.0,1.00,C.Doucouré,True,NaN,NaN,2223
27,1,0,Crystal Palace,Arsenal,2022-08-05T19:00:00Z,Chris Richards,2,4.5,1.00,Richards,True,NaN,NaN,2223
28,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Tom Cairney,3,5.0,1.00,Cairney,True,NaN,NaN,2223
29,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Tim Ream,2,4.5,1.00,Ream,True,NaN,NaN,2223
30,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Anthony Knockaert,3,5.0,1.00,Knockaert,True,NaN,NaN,2223
31,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Nathaniel Chalobah,3,4.5,0.25,Chalobah,True,NaN,NaN,2223
32,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Neeskens Kebano,3,5.5,1.00,Kebano,True,NaN,NaN,2223
33,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Bobby De Cordova-Reid,3,5.5,1.00,De Cordova-Reid,True,NaN,NaN,2223
34,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Joe Bryan,2,4.5,0.25,Bryan,True,NaN,NaN,2223
35,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Paulo Gazzaniga Farias,1,4.0,1.00,Gazzaniga,True,NaN,NaN,2223
36,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Terence Kongolo,2,4.0,1.00,Kongolo,True,NaN,NaN,2223
37,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Tosin Adarabioyo,2,4.5,1.00,Tosin,True,NaN,NaN,2223
38,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Aleksandar Mitrović,4,6.5,1.00,Mitrović,True,NaN,NaN,2223
39,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Harrison Reed,3,4.5,1.00,Reed,True,NaN,NaN,2223
40,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Harry Wilson,3,6.0,0.25,Wilson,True,NaN,NaN,2223
41,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Marek Rodák,1,4.5,1.00,Rodák,True,NaN,NaN,2223
42,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Ivan Neves Abreu Cavaleiro,3,5.0,1.00,Cavaleiro,True,NaN,NaN,2223
43,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Kenny Tete,2,4.5,1.00,Tete,True,NaN,NaN,2223
44,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Josh Onomah,3,4.5,1.00,Onomah,True,NaN,NaN,2223
45,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Antonee Robinson,2,4.5,1.00,Robinson,True,NaN,NaN,2223
46,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Rodrigo Muniz Carvalho,4,5.5,1.00,Muniz,True,NaN,NaN,2223
47,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Jay Stansfield,4,4.5,1.00,Stansfield,True,NaN,NaN,2223
48,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,João Palhinha Gonçalves,3,5.0,1.00,Palhinha,True,NaN,NaN,2223
49,1,1,Fulham,Liverpool,2022-08-06T11:30:00Z,Andreas Hoelgebaum Pereira,3,4.5,1.00,Andreas,True,NaN,NaN,2223

In [22]:
# save latest prediction set to csv
remaining_season_df.to_csv(path/'remaining_season.csv')